//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMWeb_Business.Model.MapObjectCreator
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;//[DataContract],[DataMember]
    [DataContract]
    public partial class Mdl_QuyetDinh
    {
    	[DataMember]
        public System.Guid Oid { get; set; }
    	[DataMember]
        public Nullable<byte> CoQuanRaQuyetDinh { get; set; }
    	[DataMember]
        public Nullable<System.Guid> ThongTinTruong { get; set; }
    	[DataMember]
        public string TenCoQuan { get; set; }
    	[DataMember]
        public string SoQuyetDinh { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> NgayQuyetDinh { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> NgayHieuLuc { get; set; }
    	[DataMember]
        public string CanCu { get; set; }
    	[DataMember]
        public string NoiDung { get; set; }
    	[DataMember]
        public Nullable<System.Guid> CapQuyetDinh { get; set; }
    	[DataMember]
        public Nullable<byte> PhanLoaiNguoiKy { get; set; }
    	[DataMember]
        public Nullable<System.Guid> ChucVuNguoiKy { get; set; }
    	[DataMember]
        public Nullable<System.Guid> NguoiKy { get; set; }
    	[DataMember]
        public string NguoiKy1 { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> CreateDate { get; set; }
    	[DataMember]
        public string NhanVienText { get; set; }
    	[DataMember]
        public string BoPhanText { get; set; }
    	[DataMember]
        public Nullable<int> OptimisticLockField { get; set; }
    	[DataMember]
        public Nullable<int> GCRecord { get; set; }
    	[DataMember]
        public Nullable<int> ObjectType { get; set; }
    	[DataMember]
        public Nullable<int> DaCapNhat { get; set; }
    
    	//[DataMember]
        //public virtual Mdl_ChucVu ChucVu { get; set; }
    	//[DataMember]
        //public virtual Mdl_ThongTinNhanVien ThongTinNhanVien { get; set; }
    	//[DataMember]
        //public virtual Mdl_QuyetDinhCaNhan QuyetDinhCaNhan { get; set; }
    }
}
