//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMWeb_Business.Model.MapObjectCreator
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;//[DataContract],[DataMember]
    [DataContract]
    public partial class Mdl_CC_ChamCongNgoaiGioTheoNgay
    {
    	[DataMember]
        public System.Guid Oid { get; set; }
    	[DataMember]
        public Nullable<System.Guid> IDNhanVien { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> Ngay { get; set; }
    	[DataMember]
        public Nullable<System.Guid> IDBoPhan { get; set; }
    	[DataMember]
        public Nullable<decimal> SoCongNgoaiGio { get; set; }
    	[DataMember]
        public Nullable<decimal> SoCongNgoaiGioSau23Gio { get; set; }
    	[DataMember]
        public Nullable<decimal> SoCongNgoaiGioT7CN { get; set; }
    	[DataMember]
        public Nullable<decimal> SoCongNgoaiGioT7CNSau23Gio { get; set; }
    	[DataMember]
        public Nullable<decimal> SoCongNgoaiGioLe { get; set; }
    	[DataMember]
        public Nullable<decimal> SoCongNgoaiGioLeSau23Gio { get; set; }
    	[DataMember]
        public Nullable<System.Guid> IDUser { get; set; }
    	[DataMember]
        public string TuGio { get; set; }
    	[DataMember]
        public string DenGio { get; set; }
    	[DataMember]
        public Nullable<bool> DaSuaTrenWeb { get; set; }
    
    	//[DataMember]
        //public virtual Mdl_ThongTinNhanVien ThongTinNhanVien { get; set; }
    	//[DataMember]
        //public virtual Mdl_CC_ChamCongNgoaiGioTheoNgayThayDoi CC_ChamCongNgoaiGioTheoNgayThayDoi { get; set; }
    	//[DataMember]
        //public virtual Mdl_BoPhan BoPhan { get; set; }
    }
}
