//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMWeb_Business.Model.MapObjectCreator
{
    using System;
    
    using System.Runtime.Serialization;
    [DataContract]
    public partial class spd_Report_CacThongTinLamCoSoTinhTraLuong_Result3
    {
    	[DataMember]
        public string HoTen { get; set; }
    	[DataMember]
        public string TenBoPhan { get; set; }
    	[DataMember]
        public Nullable<int> TongNghiPhep { get; set; }
    	[DataMember]
        public Nullable<int> TongNghiDamTang { get; set; }
    	[DataMember]
        public Nullable<int> TongNghiOm { get; set; }
    	[DataMember]
        public Nullable<int> TongNghiDamCuoi { get; set; }
    	[DataMember]
        public Nullable<int> TongNghiThaiSan { get; set; }
    	[DataMember]
        public Nullable<int> TongNghiViecRieng { get; set; }
    	[DataMember]
        public Nullable<int> TongNghiKhac { get; set; }
    	[DataMember]
        public Nullable<decimal> TongNgayCongLamViec { get; set; }
    	[DataMember]
        public Nullable<decimal> TongNgayCongHuongLuong { get; set; }
    	[DataMember]
        public Nullable<decimal> TongKhongLuong { get; set; }
    	[DataMember]
        public Nullable<decimal> TongDiHoc { get; set; }
    	[DataMember]
        public Nullable<decimal> TongBHXH { get; set; }
    	[DataMember]
        public string XepLoai { get; set; }
    	[DataMember]
        public string DienGiai { get; set; }
    }
}
