//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	  Code duoc tao boi SERVERERP\tai luc 09:33:22 ngay 03/10/2017
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
//using System.Data.EntityClient;
using System.Data.Entity.Core.EntityClient;
//using System.Data.Objects;
using System.Data.Entity.Core.Objects;
//using System.Data.Objects.DataClasses;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Runtime.Serialization;
using System.Xml.Serialization;


namespace HRMWeb_Business.Model
{
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ERPModel", Name="ChuyenMonDaoTao")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ChuyenMonDaoTao : ERP_Core.BaseEntityObject//EntityObject
    {
    	static ChuyenMonDaoTao()
    	{
    
    		AfterStaticConstruction();
        }
        static partial void AfterStaticConstruction();
    
    	public ChuyenMonDaoTao()
    	{
    
    		this.AfterConstruction();
        }
        partial void AfterConstruction();
    
        #region Factory Method
    
        /// <summary>
        /// Create a new ChuyenMonDaoTao object.
        /// </summary>
        /// <param name="oid">Initial value of the Oid property.</param>
        public static ChuyenMonDaoTao CreateChuyenMonDaoTao(System.Guid oid)
        {
            ChuyenMonDaoTao chuyenMonDaoTao = new ChuyenMonDaoTao();
            chuyenMonDaoTao.Oid = oid;
            return chuyenMonDaoTao;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public System.Guid Oid
        {
            get
            {
                return _oid;
            }
            set
            {
                if (_oid != value)
                {
        			System.Guid oldValue =  _oid;
        			bool stopChanging = false;
                    On_Oid_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("Oid");
        			if(!stopChanging)
        			{
        				_oid = StructuralObject.SetValidValue(value);
        				ReportPropertyChanged("Oid");
        				On_Oid_Changed(oldValue, _oid);//\\
        			}
                }
            }
        }
    	public static String Oid_PropertyName { get { return "Oid"; } }
        private System.Guid _oid;
        partial void On_Oid_Changing(System.Guid currentValue, ref System.Guid newValue, ref bool stopChanging);
        partial void On_Oid_Changed(System.Guid oldValue, System.Guid currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string MaQuanLy
        {
            get
            {
                return _maQuanLy;
            }
            set
            {
    			string oldValue =  _maQuanLy;
    			bool stopChanging = false;
                On_MaQuanLy_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("MaQuanLy");
    			if(!stopChanging)
    			{
    				_maQuanLy = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("MaQuanLy");
    				On_MaQuanLy_Changed(oldValue, _maQuanLy);//\\
    			}
            }
        }
    	public static String MaQuanLy_PropertyName { get { return "MaQuanLy"; } }
        private string _maQuanLy;
        partial void On_MaQuanLy_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_MaQuanLy_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string TenChuyenMonDaoTao
        {
            get
            {
                return _tenChuyenMonDaoTao;
            }
            set
            {
    			string oldValue =  _tenChuyenMonDaoTao;
    			bool stopChanging = false;
                On_TenChuyenMonDaoTao_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TenChuyenMonDaoTao");
    			if(!stopChanging)
    			{
    				_tenChuyenMonDaoTao = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("TenChuyenMonDaoTao");
    				On_TenChuyenMonDaoTao_Changed(oldValue, _tenChuyenMonDaoTao);//\\
    			}
            }
        }
    	public static String TenChuyenMonDaoTao_PropertyName { get { return "TenChuyenMonDaoTao"; } }
        private string _tenChuyenMonDaoTao;
        partial void On_TenChuyenMonDaoTao_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_TenChuyenMonDaoTao_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.Guid> NganhDaoTao
        {
            get
            {
                return _nganhDaoTao;
            }
            set
            {
    			Nullable<System.Guid> oldValue =  _nganhDaoTao;
    			bool stopChanging = false;
                On_NganhDaoTao_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("NganhDaoTao");
    			if(!stopChanging)
    			{
    				_nganhDaoTao = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("NganhDaoTao");
    				On_NganhDaoTao_Changed(oldValue, _nganhDaoTao);//\\
    			}
            }
        }
    	public static String NganhDaoTao_PropertyName { get { return "NganhDaoTao"; } }
        private Nullable<System.Guid> _nganhDaoTao;
        partial void On_NganhDaoTao_Changing(Nullable<System.Guid> currentValue, ref Nullable<System.Guid> newValue, ref bool stopChanging);
        partial void On_NganhDaoTao_Changed(Nullable<System.Guid> oldValue, Nullable<System.Guid> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> OptimisticLockField
        {
            get
            {
                return _optimisticLockField;
            }
            set
            {
    			Nullable<int> oldValue =  _optimisticLockField;
    			bool stopChanging = false;
                On_OptimisticLockField_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("OptimisticLockField");
    			if(!stopChanging)
    			{
    				_optimisticLockField = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("OptimisticLockField");
    				On_OptimisticLockField_Changed(oldValue, _optimisticLockField);//\\
    			}
            }
        }
    	public static String OptimisticLockField_PropertyName { get { return "OptimisticLockField"; } }
        private Nullable<int> _optimisticLockField;
        partial void On_OptimisticLockField_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_OptimisticLockField_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> GCRecord
        {
            get
            {
                return _gCRecord;
            }
            set
            {
    			Nullable<int> oldValue =  _gCRecord;
    			bool stopChanging = false;
                On_GCRecord_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("GCRecord");
    			if(!stopChanging)
    			{
    				_gCRecord = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("GCRecord");
    				On_GCRecord_Changed(oldValue, _gCRecord);//\\
    			}
            }
        }
    	public static String GCRecord_PropertyName { get { return "GCRecord"; } }
        private Nullable<int> _gCRecord;
        partial void On_GCRecord_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_GCRecord_Changed(Nullable<int> oldValue, Nullable<int> currentValue);

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ERPModel", "FK_Web_UpdateHoSoNhanVien_ChuyenNganhDaoTao", "Web_UpdateHoSoNhanVien")]
        public EntityCollection<Web_UpdateHoSoNhanVien> Web_UpdateHoSoNhanVien
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Web_UpdateHoSoNhanVien>("ERPModel.FK_Web_UpdateHoSoNhanVien_ChuyenNganhDaoTao", "Web_UpdateHoSoNhanVien");
            }
            set
            {
                if ((value != null))
                {
    				bool stopChanging = false;
    				On_Web_UpdateHoSoNhanVien_Changing(ref value, ref stopChanging);//\\//
    				if(!stopChanging)
    				{
    					((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Web_UpdateHoSoNhanVien>("ERPModel.FK_Web_UpdateHoSoNhanVien_ChuyenNganhDaoTao", "Web_UpdateHoSoNhanVien", value);
    					On_Web_UpdateHoSoNhanVien_Changed(this.Web_UpdateHoSoNhanVien);//\\//
    				}
    			}
            }
        }
    	public static String Web_UpdateHoSoNhanVien_EntityCollectionPropertyName { get { return "Web_UpdateHoSoNhanVien"; } }
    	partial void On_Web_UpdateHoSoNhanVien_Changing(ref EntityCollection<Web_UpdateHoSoNhanVien> newValue, ref bool stopChanging);
    	partial void On_Web_UpdateHoSoNhanVien_Changed(EntityCollection<Web_UpdateHoSoNhanVien> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ERPModel", "FK_NhanVienTrinhDo_ChuyenMonDaoTao", "NhanVienTrinhDo")]
        public EntityCollection<NhanVienTrinhDo> NhanVienTrinhDoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<NhanVienTrinhDo>("ERPModel.FK_NhanVienTrinhDo_ChuyenMonDaoTao", "NhanVienTrinhDo");
            }
            set
            {
                if ((value != null))
                {
    				bool stopChanging = false;
    				On_NhanVienTrinhDoes_Changing(ref value, ref stopChanging);//\\//
    				if(!stopChanging)
    				{
    					((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<NhanVienTrinhDo>("ERPModel.FK_NhanVienTrinhDo_ChuyenMonDaoTao", "NhanVienTrinhDo", value);
    					On_NhanVienTrinhDoes_Changed(this.NhanVienTrinhDoes);//\\//
    				}
    			}
            }
        }
    	public static String NhanVienTrinhDoes_EntityCollectionPropertyName { get { return "NhanVienTrinhDoes"; } }
    	partial void On_NhanVienTrinhDoes_Changing(ref EntityCollection<NhanVienTrinhDo> newValue, ref bool stopChanging);
    	partial void On_NhanVienTrinhDoes_Changed(EntityCollection<NhanVienTrinhDo> currentValue);

        #endregion

    }
}
