//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMWeb_Business.Model.MapObjectCreator
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;//[DataContract],[DataMember]
    [DataContract]
    public partial class Mdl_CC_LyDoDangKyChamCongNgoaiGio
    {
        /*
    	ko xai
    	public Mdl_CC_LyDoDangKyChamCongNgoaiGio()
        {
            this.CC_DangKyChamCongNgoaiGio = new HashSet<Mdl_CC_DangKyChamCongNgoaiGio>();
        }*/
    
    	[DataMember]
        public System.Guid Oid { get; set; }
    	[DataMember]
        public string LyDo { get; set; }
    
    	//[DataMember]
        //public virtual ICollection<Mdl_CC_DangKyChamCongNgoaiGio> CC_DangKyChamCongNgoaiGio { get; set; }
    }
}
