//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace HRMWeb_Business.Model
{
    using System;
    using System.Collections.Generic;
    [DataContract]
    public partial class DTO_BoPhan
    {
        [DataMember] 
        public System.Guid Oid { get; set; }
        [DataMember] 
        public string MaQuanLy { get; set; }
        [DataMember] 
        public Nullable<decimal> STT { get; set; }
        [DataMember] 
        public string TenBoPhan { get; set; }
        [DataMember] 
        public Nullable<byte> LoaiBoPhan { get; set; }
        [DataMember] 
        public Nullable<System.Guid> BoPhanCha { get; set; }
        [DataMember]
        public bool Chon { get; set; }
        [DataMember]
        public string TenBoPhanFull { get; set; }
        [DataMember]
        public Nullable<System.Guid> CongTy { get; set; }

    }
}
