//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace HRMWeb_Business.Model
{
    using System;
    using System.Collections.Generic;
    [DataContract]
    public partial class DTO_CC_CauHinhChamCong
    {
        [DataMember] 
        public System.Guid Oid { get; set; }
        [DataMember] 
        public string EmailSender { get; set; }
        [DataMember]
        public string PassSender { get; set; }
        [DataMember] 
        public string Host { get; set; }
        [DataMember]
        public int? Port { get; set; }

        [DataMember]
        public int SoNgayNghiPhep { get; set; }

        [DataMember]
        public int SoNgayHieuTruongDuyet { get; set; }

        [DataMember]
        public int SoNgayDangKyNgoaiGio { get; set; }

        [DataMember]
        public DateTime? NgayXoaPhepCu { get; set; }

        [DataMember]
        public decimal? SoNgayPhepTangThem { get; set; }

        [DataMember]
        public decimal? ThoiGianTangSoNgayPhep { get; set; }

        [DataMember]
        public bool? TruongDonViKhongDuyet { get; set; }
    }
}
