//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace HRMWeb_Business.Model
{
    using System;
    using System.Collections.Generic;
    [DataContract]
    public partial class DTO_QuanLyGuiMail
    {
        [DataMember]
        public Guid Oid { get; set; }

        [DataMember]
        public string Title { get; set; }

        [DataMember]
        public string Contents { get; set; }

        [DataMember]
        public string ReceiverEmail { get; set; }

        [DataMember]
        public string SendEmail { get; set; }

        [DataMember]
        public string SendPass { get; set; }

        [DataMember]
        public DateTime SendDate { get; set; }

        [DataMember]
        public string FileName { get; set; }
    }
}
