//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace HRMWeb_Business.Model
{
    using System;
    using System.Collections.Generic;
    [DataContract]
    public partial class DTO_ChiTietChamCong_Find
    {
        //Them vao
        [DataMember]
        public String MaNhanSu { get; set; }
        [DataMember]
        public String HoTen { get; set; }
        [DataMember]
        public String TenPhongBan { get; set; }
        [DataMember]
        public System.Guid Oid { get; set; }
        [DataMember]
        public Nullable<Decimal> NgayCongChuan { get; set; }
        [DataMember]
        public Nullable<Decimal> NgayCongThucTe  { get; set; }
        [DataMember]
        public Nullable<Decimal> NgayCongCangTra { get; set; }
        [DataMember]
        public Nullable<Decimal> NgayCongNghi { get; set; }
        [DataMember]
        public Nullable<Decimal> NgayCongSuaChua { get; set; }
        [DataMember]
        public Nullable<Decimal> NgayCongLamLe { get; set; }
        [DataMember]
        public Nullable<Decimal> NgayCongNghiLe { get; set; }
        [DataMember]
        public Nullable<Decimal> NgayCongAnCa { get; set; }
        [DataMember]
        public Nullable<Decimal> NgayCongDocHai { get; set; }
        [DataMember]
        public Nullable<Decimal> NgayCongLamDem { get; set; }
        [DataMember]
        public Nullable<Decimal> NgayNghiPhep { get; set; }
        [DataMember]
        public Nullable<Decimal> NgayNghiKhongPhep { get; set; }
        [DataMember]
        public Nullable<Decimal> NgayNghiThaiSan { get; set; }
        [DataMember]
        public string XepLoaiCanBo { get; set; }
        [DataMember]
        public Nullable<Decimal> HeSoXepLoai { get; set; }
        [DataMember]
        public Nullable<Decimal> HeSoNgayCong { get; set; }


    }
}
