//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	  Code duoc tao boi SERVERERP\tai luc 05:27:29 ngay 19/04/2017
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
//using System.Data.EntityClient;
using System.Data.Entity.Core.EntityClient;
//using System.Data.Objects;
using System.Data.Entity.Core.Objects;
//using System.Data.Objects.DataClasses;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Runtime.Serialization;
using System.Xml.Serialization;


namespace HRMWeb_Business.Model
{
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ERPModel", Name="CC_QuanLyNghiPhep")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CC_QuanLyNghiPhep : ERP_Core.BaseEntityObject//EntityObject
    {
    	static CC_QuanLyNghiPhep()
    	{
    
    		AfterStaticConstruction();
        }
        static partial void AfterStaticConstruction();
    
    	public CC_QuanLyNghiPhep()
    	{
    
    		this.AfterConstruction();
        }
        partial void AfterConstruction();
    
        #region Factory Method
    
        /// <summary>
        /// Create a new CC_QuanLyNghiPhep object.
        /// </summary>
        /// <param name="oid">Initial value of the Oid property.</param>
        public static CC_QuanLyNghiPhep CreateCC_QuanLyNghiPhep(System.Guid oid)
        {
            CC_QuanLyNghiPhep cC_QuanLyNghiPhep = new CC_QuanLyNghiPhep();
            cC_QuanLyNghiPhep.Oid = oid;
            return cC_QuanLyNghiPhep;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public System.Guid Oid
        {
            get
            {
                return _oid;
            }
            set
            {
                if (_oid != value)
                {
        			System.Guid oldValue =  _oid;
        			bool stopChanging = false;
                    On_Oid_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("Oid");
        			if(!stopChanging)
        			{
        				_oid = StructuralObject.SetValidValue(value);
        				ReportPropertyChanged("Oid");
        				On_Oid_Changed(oldValue, _oid);//\\
        			}
                }
            }
        }
    	public static String Oid_PropertyName { get { return "Oid"; } }
        private System.Guid _oid;
        partial void On_Oid_Changing(System.Guid currentValue, ref System.Guid newValue, ref bool stopChanging);
        partial void On_Oid_Changed(System.Guid oldValue, System.Guid currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> Nam
        {
            get
            {
                return _nam;
            }
            set
            {
    			Nullable<int> oldValue =  _nam;
    			bool stopChanging = false;
                On_Nam_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("Nam");
    			if(!stopChanging)
    			{
    				_nam = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("Nam");
    				On_Nam_Changed(oldValue, _nam);//\\
    			}
            }
        }
    	public static String Nam_PropertyName { get { return "Nam"; } }
        private Nullable<int> _nam;
        partial void On_Nam_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_Nam_Changed(Nullable<int> oldValue, Nullable<int> currentValue);

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ERPModel", "FK_CC_ChiTietNghiPhep_CC_QuanLyNghiPhep", "CC_ChiTietNghiPhep")]
        public EntityCollection<CC_ChiTietNghiPhep> CC_ChiTietNghiPhep
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CC_ChiTietNghiPhep>("ERPModel.FK_CC_ChiTietNghiPhep_CC_QuanLyNghiPhep", "CC_ChiTietNghiPhep");
            }
            set
            {
                if ((value != null))
                {
    				bool stopChanging = false;
    				On_CC_ChiTietNghiPhep_Changing(ref value, ref stopChanging);//\\//
    				if(!stopChanging)
    				{
    					((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CC_ChiTietNghiPhep>("ERPModel.FK_CC_ChiTietNghiPhep_CC_QuanLyNghiPhep", "CC_ChiTietNghiPhep", value);
    					On_CC_ChiTietNghiPhep_Changed(this.CC_ChiTietNghiPhep);//\\//
    				}
    			}
            }
        }
    	public static String CC_ChiTietNghiPhep_EntityCollectionPropertyName { get { return "CC_ChiTietNghiPhep"; } }
    	partial void On_CC_ChiTietNghiPhep_Changing(ref EntityCollection<CC_ChiTietNghiPhep> newValue, ref bool stopChanging);
    	partial void On_CC_ChiTietNghiPhep_Changed(EntityCollection<CC_ChiTietNghiPhep> currentValue);

        #endregion

    }
}
