//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace HRMWeb_Business.Model
{
    using System;
    using System.Collections.Generic;
    [DataContract]
    public partial class DTO_CC_KhaiBaoChamCongGiangVien
    {
        [DataMember]
        public byte Buoi { get; set; }
        [DataMember]
        public DateTime TuNgay { get; set; }
        [DataMember]
        public DateTime DenNgay { get; set; }
        [DataMember]
        public Guid ThongTinNhanVien { get; set; }
        [DataMember]
        public IEnumerable<DTO_Thu> DanhSachDTO_Thu { get; set; }
    }
}
