//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace HRMWeb_Business.Model
{
    using System;
    using System.Collections.Generic;
    [DataContract]
    public partial class DTO_CC_DangKyChamCongNgoaiGio
    {
        [DataMember]
        public Guid Oid { get; set; }
        [DataMember]
        public Nullable<System.DateTime> Ngay { get; set; }
        [DataMember]
        public DateTime TuNgay { get; set; }
        [DataMember]
        public DateTime DenNgay { get; set; }
        [DataMember]
        public Nullable<System.Decimal> SoGio { get; set; }
        [DataMember]
        public string LyDo { get; set; }
        [DataMember]
        public Nullable<System.Byte> Duyet { get; set; }
        [DataMember]
        public Nullable<System.Byte> DuyetAdmin { get; set; }
        [DataMember]
        public string ThongTinNhanVien { get; set; }
        [DataMember]
        public string HoTen { get; set; }
        [DataMember]
        public string SoHieuCongChuc { get; set; }
        [DataMember]
        public Guid BoPhanId { get; set; }
        [DataMember]
        public string BoPhan { get; set; }
        [DataMember]
        public decimal SoPhutDangKy { get; set; }
        [DataMember]
        public decimal SoPhutThucTe { get; set; }
        [DataMember]
        public IEnumerable<DTO_Thu> DanhSachDTO_Thu { get; set; }
        [DataMember]
        public int GioBatDau { get; set; }
        [DataMember]
        public int PhutBatDau { get; set; }
        [DataMember]
        public int GioKetThuc { get; set; }
        [DataMember]
        public int PhutKetThuc { get; set; }
        [DataMember]
        public string ThoiGianBatDau { get; set; }
        [DataMember]
        public string ThoiGianKetThuc { get; set; }
        [DataMember]
        public string TrangThai { get; set; }

        /// <summary>
        /// Phụ vụ báo cáo
        /// </summary> 
        [DataMember]
        public string NgayString { get; set; }
        [DataMember]
        public string NgayBaoCao { get; set; }
        [DataMember]
        public string ThoiGianBaoCao { get; set; }

        [DataMember]
        public decimal DonGia { get; set; }

        [DataMember]
        public decimal ThanhTien { get; set; }

        [DataMember]
        public decimal SoCongNgoaiGio { get; set; }
    }
}
