//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace HRMWeb_Business.Model
{
    using System;
    using System.Collections.Generic;
    [DataContract]
    public partial class DTO_QuanLyChamCong_ChamCongNgay
    {


        [DataMember]
        public System.Guid CC_ChamCongTheoNgayOid { get; set; }

        [DataMember]
        public System.Guid IDNhanVien { get; set; }

        [DataMember]
        public DateTime Ngay { get; set; }

        [DataMember]
        public String MaHinhThucNghi { get; set; }

        [DataMember]
        public DateTime? GioVaoSang { get; set; }

        [DataMember]
        public DateTime? GioRaChieu { get; set; }

        [DataMember]
        public IEnumerable<DTO_CC_QuanLyViPham> QuanLyViPham { get; set; }

        [DataMember]
        public int QuanLyViPhamCount { get; set; }

        [DataMember]
        public string GhiChu { get; set; }
    }
}
