//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	  Code duoc tao boi DESKTOP-PKPRC2J\NGOCBAO luc 04:17:16 ngay 30/08/2016
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
//using System.Data.EntityClient;
using System.Data.Entity.Core.EntityClient;
//using System.Data.Objects;
using System.Data.Entity.Core.Objects;
//using System.Data.Objects.DataClasses;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Runtime.Serialization;
using System.Xml.Serialization;


namespace HRMWeb_Business.Model.Context
{
    /// <summary>
    /// Interface for Entities
    /// </summary>
    public partial interface IEntities
    {
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        IObjectSet<WebUser_BoPhan> WebUser_BoPhan { get; }
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        IObjectSet<BoPhan> BoPhans { get; }
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        IObjectSet<HinhThucNghi> HinhThucNghis { get; }
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        IObjectSet<NhanVien> NhanViens { get; }
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        IObjectSet<QuanLyChamCongNhanVien> QuanLyChamCongNhanViens { get; }
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        IObjectSet<WebGroup> WebGroups { get; }
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        IObjectSet<WebMenu> WebMenus { get; }
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        IObjectSet<WebMenu_Role> WebMenu_Role { get; }
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        IObjectSet<ThongTinNhanVien> ThongTinNhanViens { get; }
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        IObjectSet<LoaiNhanSu> LoaiNhanSus { get; }
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        IObjectSet<TinhTrang> TinhTrangs { get; }
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        IObjectSet<CC_ChamCong> CC_ChamCong { get; }
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        IObjectSet<CC_ChamCongTheoNgay> CC_ChamCongTheoNgay { get; }
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        IObjectSet<KyTinhLuong> KyTinhLuongs { get; }
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        IObjectSet<CC_KhaiBaoCongTac> CC_KhaiBaoCongTac { get; }
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        IObjectSet<CC_ChamCongNgayNghi> CC_ChamCongNgayNghi { get; }
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        IObjectSet<BangChotThongTinTinhLuong> BangChotThongTinTinhLuongs { get; }
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        IObjectSet<BangLuongNhanVien> BangLuongNhanViens { get; }
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        IObjectSet<DangLuuTru> DangLuuTrus { get; }
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        IObjectSet<GiayToHoSo> GiayToHoSoes { get; }
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        IObjectSet<GiayTo> GiayToes { get; }
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        IObjectSet<Web_GiayChungNhan_AutoNumber> Web_GiayChungNhan_AutoNumber { get; }
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        IObjectSet<CauHinhXetABC> CauHinhXetABCs { get; }
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        IObjectSet<WebUser> WebUsers { get; }
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        IObjectSet<HoSo> HoSoes { get; }
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        IObjectSet<ChiTietChamCongNhanVien> ChiTietChamCongNhanViens { get; }
    

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WebUser_BoPhan EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        void AddToWebUser_BoPhan(WebUser_BoPhan webUser_BoPhan);
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BoPhans EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        void AddToBoPhans(BoPhan boPhan);
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HinhThucNghis EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        void AddToHinhThucNghis(HinhThucNghi hinhThucNghi);
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NhanViens EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        void AddToNhanViens(NhanVien nhanVien);
    
        /// <summary>
        /// Deprecated Method for adding a new object to the QuanLyChamCongNhanViens EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        void AddToQuanLyChamCongNhanViens(QuanLyChamCongNhanVien quanLyChamCongNhanVien);
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WebGroups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        void AddToWebGroups(WebGroup webGroup);
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WebMenus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        void AddToWebMenus(WebMenu webMenu);
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WebMenu_Role EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        void AddToWebMenu_Role(WebMenu_Role webMenu_Role);
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ThongTinNhanViens EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        void AddToThongTinNhanViens(ThongTinNhanVien thongTinNhanVien);
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LoaiNhanSus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        void AddToLoaiNhanSus(LoaiNhanSu loaiNhanSu);
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TinhTrangs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        void AddToTinhTrangs(TinhTrang tinhTrang);
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CC_ChamCong EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        void AddToCC_ChamCong(CC_ChamCong cC_ChamCong);
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CC_ChamCongTheoNgay EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        void AddToCC_ChamCongTheoNgay(CC_ChamCongTheoNgay cC_ChamCongTheoNgay);
    
        /// <summary>
        /// Deprecated Method for adding a new object to the KyTinhLuongs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        void AddToKyTinhLuongs(KyTinhLuong kyTinhLuong);
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CC_KhaiBaoCongTac EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        void AddToCC_KhaiBaoCongTac(CC_KhaiBaoCongTac cC_KhaiBaoCongTac);
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CC_ChamCongNgayNghi EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        void AddToCC_ChamCongNgayNghi(CC_ChamCongNgayNghi cC_ChamCongNgayNghi);
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BangChotThongTinTinhLuongs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        void AddToBangChotThongTinTinhLuongs(BangChotThongTinTinhLuong bangChotThongTinTinhLuong);
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BangLuongNhanViens EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        void AddToBangLuongNhanViens(BangLuongNhanVien bangLuongNhanVien);
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DangLuuTrus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        void AddToDangLuuTrus(DangLuuTru dangLuuTru);
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GiayToHoSoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        void AddToGiayToHoSoes(GiayToHoSo giayToHoSo);
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GiayToes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        void AddToGiayToes(GiayTo giayTo);
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Web_GiayChungNhan_AutoNumber EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        void AddToWeb_GiayChungNhan_AutoNumber(Web_GiayChungNhan_AutoNumber web_GiayChungNhan_AutoNumber);
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CauHinhXetABCs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        void AddToCauHinhXetABCs(CauHinhXetABC cauHinhXetABC);
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WebUsers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        void AddToWebUsers(WebUser webUser);
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HoSoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        void AddToHoSoes(HoSo hoSo);
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ChiTietChamCongNhanViens EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        void AddToChiTietChamCongNhanViens(ChiTietChamCongNhanVien chiTietChamCongNhanVien);

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="thang">No Metadata Documentation available.</param>
        /// <param name="nam">No Metadata Documentation available.</param>
        /// <param name="hinhThucNghi">No Metadata Documentation available.</param>
        /// <param name="webUserId">No Metadata Documentation available.</param>
        /// <param name="daChamCong">No Metadata Documentation available.</param>
        int spd_WebChamCong_TaoDanhSach_CC_ChamCongTheoNgay_ChoCaThang(Nullable<int> thang, Nullable<int> nam, Nullable<System.Guid> hinhThucNghi, Nullable<System.Guid> webUserId, Nullable<bool> daChamCong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="ngay">No Metadata Documentation available.</param>
        /// <param name="thang">No Metadata Documentation available.</param>
        /// <param name="nam">No Metadata Documentation available.</param>
        /// <param name="idHinhThucNghi">No Metadata Documentation available.</param>
        /// <param name="daChamCong">No Metadata Documentation available.</param>
        /// <param name="idBoPhan">No Metadata Documentation available.</param>
        /// <param name="idLoaiNhanSu">No Metadata Documentation available.</param>
        /// <param name="webUserId">No Metadata Documentation available.</param>
        int spd_WebChamCong_ChamCongHangLoatDonVi(Nullable<int> ngay, Nullable<int> thang, Nullable<int> nam, Nullable<System.Guid> idHinhThucNghi, Nullable<bool> daChamCong, Nullable<System.Guid> idBoPhan, Nullable<System.Guid> idLoaiNhanSu, Nullable<System.Guid> webUserId);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="iDNhanVien">No Metadata Documentation available.</param>
        /// <param name="tuNgay">No Metadata Documentation available.</param>
        /// <param name="denNgay">No Metadata Documentation available.</param>
        /// <param name="iDHinhThucNghi">No Metadata Documentation available.</param>
        /// <param name="daChamCong">No Metadata Documentation available.</param>
        int spd_WebChamCong_CC_ChamCongTheoNgay_CapNhatHinhThucNghi_VaTrangThaiChamCong(Nullable<System.Guid> iDNhanVien, Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, Nullable<System.Guid> iDHinhThucNghi, Nullable<bool> daChamCong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="iDNhanVien">No Metadata Documentation available.</param>
        /// <param name="tuNgay">No Metadata Documentation available.</param>
        /// <param name="denNgay">No Metadata Documentation available.</param>
        /// <param name="daChamCong">No Metadata Documentation available.</param>
        int spd_WebChamCong_CC_ChamCongTheoNgay_CapNhatTrangThaiChamCong(Nullable<System.Guid> iDNhanVien, Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, Nullable<bool> daChamCong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuanHeGiaDinh_Result> spd_Web1_QuanHeGiaDinh(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        /// <param name="kyTinhLuong">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ChiTietKhauTruLuong_Result> spd_Web1_ChiTietKhauTruLuong(Nullable<System.Guid> nhanVien, Nullable<System.Guid> kyTinhLuong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        /// <param name="kyTinhLuong">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ChiTietKhenThuongPhucLoi_Result> spd_Web1_ChiTietKhenThuongPhucLoi(Nullable<System.Guid> nhanVien, Nullable<System.Guid> kyTinhLuong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        /// <param name="kyTinhLuong">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ChiTietNgoaiGio_Result> spd_Web1_ChiTietNgoaiGio(Nullable<System.Guid> nhanVien, Nullable<System.Guid> kyTinhLuong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        /// <param name="kyTinhLuong">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ChiTietPhuCap_Result> spd_Web1_ChiTietPhuCap(Nullable<System.Guid> nhanVien, Nullable<System.Guid> kyTinhLuong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        /// <param name="kyTinhLuong">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ChiTietThueTNCN_Result> spd_Web1_ChiTietThueTNCN(Nullable<System.Guid> nhanVien, Nullable<System.Guid> kyTinhLuong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        /// <param name="kyTinhLuong">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ChiTietThuLaoGiangDay_Result> spd_Web1_ChiTietThuLaoGiangDay(Nullable<System.Guid> nhanVien, Nullable<System.Guid> kyTinhLuong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        /// <param name="kyTinhLuong">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ChiTietThuNhapCaNhan_Result> spd_Web1_ChiTietThuNhapCaNhan(Nullable<System.Guid> nhanVien, Nullable<System.Guid> kyTinhLuong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        /// <param name="kyTinhLuong">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ChiTietThuNhapKhac_Result> spd_Web1_ChiTietThuNhapKhac(Nullable<System.Guid> nhanVien, Nullable<System.Guid> kyTinhLuong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ChungChi_Result> spd_Web1_ChungChi(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_CongDoan_Result> spd_Web1_CongDoan(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_DangVien_Result> spd_Web1_DangVien(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_DienBienLuong_Result> spd_Web1_DienBienLuong(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_DoanVien_Result> spd_Web1_DoanVien(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_HopDongDaKy_Result> spd_Web1_HopDongDaKy(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_LichSuBanThan_Result> spd_Web1_LichSuBanThan(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_NgoaiNgu_Result> spd_Web1_NgoaiNgu(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_NguoiPhuThuoc_Result> spd_Web1_NguoiPhuThuoc(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhBoiDuong_Result> spd_Web1_QuaTrinhBoiDuong(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhBoNhiem_Result> spd_Web1_QuaTrinhBoNhiem(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhCongTac_Result> spd_Web1_QuaTrinhCongTac(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhDaoTao_Result> spd_Web1_QuaTrinhDaoTao(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhDiNuocNgoai_Result> spd_Web1_QuaTrinhDiNuocNgoai(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhKhenThuong_Result> spd_Web1_QuaTrinhKhenThuong(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhKyLuat_Result> spd_Web1_QuaTrinhKyLuat(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhNghienCuuKhoaHoc_Result> spd_Web1_QuaTrinhNghienCuuKhoaHoc(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhThamGiaBHXH_Result> spd_Web1_QuaTrinhThamGiaBHXH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhThamGiaHoatDongXaHoi_Result> spd_Web1_QuaTrinhThamGiaHoatDongXaHoi(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhThamGiaHoiThao_Result> spd_Web1_QuaTrinhThamGiaHoiThao(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_TaiKhoanNganHang_Result> spd_Web1_TaiKhoanNganHang(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_TrinhDoChuyenMon_Result> spd_Web1_TrinhDoChuyenMon(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_VanBang_Result> spd_Web1_VanBang(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhThamGiaLucLuongVuTrang_Result> spd_Web1_QuaTrinhThamGiaLucLuongVuTrang(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_HoSoBaoHiem_Result> spd_Web1_HoSoBaoHiem(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_HopDong_Result> spd_Web1_HopDong(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="thang">No Metadata Documentation available.</param>
        /// <param name="nam">No Metadata Documentation available.</param>
        /// <param name="quanLyChamCongNhanVienOid">No Metadata Documentation available.</param>
        /// <param name="boPhanID">No Metadata Documentation available.</param>
        int spd_WebChamCong_ChotChamCongThang_CapNhatSoNgayCongNgayNghi(Nullable<int> thang, Nullable<int> nam, Nullable<System.Guid> quanLyChamCongNhanVienOid, Nullable<System.Guid> boPhanID);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="thang">No Metadata Documentation available.</param>
        /// <param name="nam">No Metadata Documentation available.</param>
        /// <param name="boPhanID">No Metadata Documentation available.</param>
        int spd_WebChamCong_ChotChamCongThang_Delete(Nullable<int> thang, Nullable<int> nam, Nullable<System.Guid> boPhanID);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="thongTinNhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_GiayChungNhan_Result> spd_Web1_GiayChungNhan(Nullable<System.Guid> thongTinNhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="thongTinNhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_GiayChungNhanCanBoVienChucTruong_Result> spd_Web1_GiayChungNhanCanBoVienChucTruong(Nullable<System.Guid> thongTinNhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ThongTinLuong_Result> spd_Web1_ThongTinLuong(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_SoYeuLyLich_Result> spd_Web1_SoYeuLyLich(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        /// <param name="kyTinhLuong">No Metadata Documentation available.</param>
        /// <param name="loaiLuong">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ChiTietKhauTruLuong_IUH_Result> spd_Web1_ChiTietKhauTruLuong_IUH(Nullable<System.Guid> nhanVien, Nullable<System.Guid> kyTinhLuong, Nullable<byte> loaiLuong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        /// <param name="kyTinhLuong">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ChiTietThueTNCN_IUH_Result> spd_Web1_ChiTietThueTNCN_IUH(Nullable<System.Guid> nhanVien, Nullable<System.Guid> kyTinhLuong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        /// <param name="kyTinhLuong">No Metadata Documentation available.</param>
        /// <param name="loaiLuong">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ChiTietThuNhapCaNhan_IUH_Result> spd_Web1_ChiTietThuNhapCaNhan_IUH(Nullable<System.Guid> nhanVien, Nullable<System.Guid> kyTinhLuong, Nullable<byte> loaiLuong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_SoYeuLyLich_IUH_Result> spd_Web1_SoYeuLyLich_IUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_NguoiPhuThuoc_IUH_Result> spd_Web1_NguoiPhuThuoc_IUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_TaiKhoanNganHang_IUH_Result> spd_Web1_TaiKhoanNganHang_IUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ThongTinLuong_IUH_Result> spd_Web1_ThongTinLuong_IUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ChungChi_IUH_Result> spd_Web1_ChungChi_IUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_TrinhDoChuyenMon_IUH_Result> spd_Web1_TrinhDoChuyenMon_IUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_VanBang_IUH_Result> spd_Web1_VanBang_IUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_NgoaiNgu_IUH_Result> spd_Web1_NgoaiNgu_IUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_CongDoan_IUH_Result> spd_Web1_CongDoan_IUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_DangVien_IUH_Result> spd_Web1_DangVien_IUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_DoanVien_IUH_Result> spd_Web1_DoanVien_IUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_HopDong_IUH_Result> spd_Web1_HopDong_IUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_HopDongDaKy_IUH_Result> spd_Web1_HopDongDaKy_IUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuanHeGiaDinh_IUH_Result> spd_Web1_QuanHeGiaDinh_IUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_DienBienLuong_IUH_Result> spd_Web1_DienBienLuong_IUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_LichSuBanThan_IUH_Result> spd_Web1_LichSuBanThan_IUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhBoiDuong_IUH_Result> spd_Web1_QuaTrinhBoiDuong_IUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhBoNhiem_IUH_Result> spd_Web1_QuaTrinhBoNhiem_IUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhCongTac_IUH_Result> spd_Web1_QuaTrinhCongTac_IUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhDaoTao_IUH_Result> spd_Web1_QuaTrinhDaoTao_IUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhDiNuocNgoai_IUH_Result> spd_Web1_QuaTrinhDiNuocNgoai_IUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhKhenThuong_IUH_Result> spd_Web1_QuaTrinhKhenThuong_IUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhKyLuat_IUH_Result> spd_Web1_QuaTrinhKyLuat_IUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhNghienCuuKhoaHoc_IUH_Result> spd_Web1_QuaTrinhNghienCuuKhoaHoc_IUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhThamGiaHoatDongXaHoi_IUH_Result> spd_Web1_QuaTrinhThamGiaHoatDongXaHoi_IUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhThamGiaHoiThao_IUH_Result> spd_Web1_QuaTrinhThamGiaHoiThao_IUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhThamGiaLucLuongVuTrang_IUH_Result> spd_Web1_QuaTrinhThamGiaLucLuongVuTrang_IUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="thongTinNhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_GiayChungNhan_IUH_Result> spd_Web1_GiayChungNhan_IUH(Nullable<System.Guid> thongTinNhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="thongTinNhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_GiayChungNhanCanBoVienChucTruong_IUH_Result> spd_Web1_GiayChungNhanCanBoVienChucTruong_IUH(Nullable<System.Guid> thongTinNhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        /// <param name="kyTinhLuong">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ChiTietKhauTruLuong_HRM3_Result> spd_Web1_ChiTietKhauTruLuong_HRM3(Nullable<System.Guid> nhanVien, Nullable<System.Guid> kyTinhLuong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        /// <param name="kyTinhLuong">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ChiTietKhenThuongPhucLoi_HRM3_Result> spd_Web1_ChiTietKhenThuongPhucLoi_HRM3(Nullable<System.Guid> nhanVien, Nullable<System.Guid> kyTinhLuong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        /// <param name="kyTinhLuong">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ChiTietNgoaiGio_HRM3_Result> spd_Web1_ChiTietNgoaiGio_HRM3(Nullable<System.Guid> nhanVien, Nullable<System.Guid> kyTinhLuong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        /// <param name="kyTinhLuong">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ChiTietPhuCap_HRM3_Result> spd_Web1_ChiTietPhuCap_HRM3(Nullable<System.Guid> nhanVien, Nullable<System.Guid> kyTinhLuong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        /// <param name="kyTinhLuong">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ChiTietThueTNCN_HRM3_Result> spd_Web1_ChiTietThueTNCN_HRM3(Nullable<System.Guid> nhanVien, Nullable<System.Guid> kyTinhLuong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        /// <param name="kyTinhLuong">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ChiTietThuLaoGiangDay_HRM3_Result> spd_Web1_ChiTietThuLaoGiangDay_HRM3(Nullable<System.Guid> nhanVien, Nullable<System.Guid> kyTinhLuong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        /// <param name="kyTinhLuong">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ChiTietThuNhapCaNhan_HRM3_Result> spd_Web1_ChiTietThuNhapCaNhan_HRM3(Nullable<System.Guid> nhanVien, Nullable<System.Guid> kyTinhLuong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        /// <param name="kyTinhLuong">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ChiTietThuNhapKhac_HRM3_Result> spd_Web1_ChiTietThuNhapKhac_HRM3(Nullable<System.Guid> nhanVien, Nullable<System.Guid> kyTinhLuong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_HoSoBaoHiem_HRM3_Result> spd_Web1_HoSoBaoHiem_HRM3(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhThamGiaBHXH_HRM3_Result> spd_Web1_QuaTrinhThamGiaBHXH_HRM3(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ChungChi_LUH_Result> spd_Web1_ChungChi_LUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_CongDoan_LUH_Result> spd_Web1_CongDoan_LUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_DangVien_LUH_Result> spd_Web1_DangVien_LUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_DienBienLuong_LUH_Result> spd_Web1_DienBienLuong_LUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_DoanVien_LUH_Result> spd_Web1_DoanVien_LUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_HopDong_LUH_Result> spd_Web1_HopDong_LUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_HopDongDaKy_LUH_Result> spd_Web1_HopDongDaKy_LUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_LichSuBanThan_LUH_Result> spd_Web1_LichSuBanThan_LUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_NgoaiNgu_LUH_Result> spd_Web1_NgoaiNgu_LUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_NguoiPhuThuoc_LUH_Result> spd_Web1_NguoiPhuThuoc_LUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuanHeGiaDinh_LUH_Result> spd_Web1_QuanHeGiaDinh_LUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhBoiDuong_LUH_Result> spd_Web1_QuaTrinhBoiDuong_LUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhBoNhiem_LUH_Result> spd_Web1_QuaTrinhBoNhiem_LUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhCongTac_LUH_Result> spd_Web1_QuaTrinhCongTac_LUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhDaoTao_LUH_Result> spd_Web1_QuaTrinhDaoTao_LUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhDiNuocNgoai_LUH_Result> spd_Web1_QuaTrinhDiNuocNgoai_LUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhKhenThuong_LUH_Result> spd_Web1_QuaTrinhKhenThuong_LUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhKyLuat_LUH_Result> spd_Web1_QuaTrinhKyLuat_LUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhNghienCuuKhoaHoc_LUH_Result> spd_Web1_QuaTrinhNghienCuuKhoaHoc_LUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhThamGiaHoatDongXaHoi_LUH_Result> spd_Web1_QuaTrinhThamGiaHoatDongXaHoi_LUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhThamGiaHoiThao_LUH_Result> spd_Web1_QuaTrinhThamGiaHoiThao_LUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhThamGiaLucLuongVuTrang_LUH_Result> spd_Web1_QuaTrinhThamGiaLucLuongVuTrang_LUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_SoYeuLyLich_LUH_Result> spd_Web1_SoYeuLyLich_LUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_TaiKhoanNganHang_LUH_Result> spd_Web1_TaiKhoanNganHang_LUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ThongTinLuong_LUH_Result> spd_Web1_ThongTinLuong_LUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_TrinhDoChuyenMon_LUH_Result> spd_Web1_TrinhDoChuyenMon_LUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_VanBang_LUH_Result> spd_Web1_VanBang_LUH(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ChungChi_UTE_Result> spd_Web1_ChungChi_UTE(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_CongDoan_UTE_Result> spd_Web1_CongDoan_UTE(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_DangVien_UTE_Result> spd_Web1_DangVien_UTE(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_DienBienLuong_UTE_Result> spd_Web1_DienBienLuong_UTE(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_DoanVien_UTE_Result> spd_Web1_DoanVien_UTE(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_HopDong_UTE_Result> spd_Web1_HopDong_UTE(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_HopDongDaKy_UTE_Result> spd_Web1_HopDongDaKy_UTE(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_LichSuBanThan_UTE_Result> spd_Web1_LichSuBanThan_UTE(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_NgoaiNgu_UTE_Result> spd_Web1_NgoaiNgu_UTE(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_NguoiPhuThuoc_UTE_Result> spd_Web1_NguoiPhuThuoc_UTE(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuanHeGiaDinh_UTE_Result> spd_Web1_QuanHeGiaDinh_UTE(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhBoiDuong_UTE_Result> spd_Web1_QuaTrinhBoiDuong_UTE(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhBoNhiem_UTE_Result> spd_Web1_QuaTrinhBoNhiem_UTE(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhCongTac_UTE_Result> spd_Web1_QuaTrinhCongTac_UTE(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhDaoTao_UTE_Result> spd_Web1_QuaTrinhDaoTao_UTE(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhDiNuocNgoai_UTE_Result> spd_Web1_QuaTrinhDiNuocNgoai_UTE(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhKhenThuong_UTE_Result> spd_Web1_QuaTrinhKhenThuong_UTE(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhKyLuat_UTE_Result> spd_Web1_QuaTrinhKyLuat_UTE(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhNghienCuuKhoaHoc_UTE_Result> spd_Web1_QuaTrinhNghienCuuKhoaHoc_UTE(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhThamGiaHoatDongXaHoi_UTE_Result> spd_Web1_QuaTrinhThamGiaHoatDongXaHoi_UTE(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhThamGiaHoiThao_UTE_Result> spd_Web1_QuaTrinhThamGiaHoiThao_UTE(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_QuaTrinhThamGiaLucLuongVuTrang_UTE_Result> spd_Web1_QuaTrinhThamGiaLucLuongVuTrang_UTE(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_SoYeuLyLich_UTE_Result> spd_Web1_SoYeuLyLich_UTE(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_TaiKhoanNganHang_UTE_Result> spd_Web1_TaiKhoanNganHang_UTE(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ThongTinLuong_UTE_Result> spd_Web1_ThongTinLuong_UTE(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_TrinhDoChuyenMon_UTE_Result> spd_Web1_TrinhDoChuyenMon_UTE(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_VanBang_UTE_Result> spd_Web1_VanBang_UTE(Nullable<System.Guid> nhanVien);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        /// <param name="kyTinhLuong">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ChiTietKhauTruLuong_LUH_Result> spd_Web1_ChiTietKhauTruLuong_LUH(Nullable<System.Guid> nhanVien, Nullable<System.Guid> kyTinhLuong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        /// <param name="kyTinhLuong">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ChiTietKhenThuongPhucLoi_LUH_Result> spd_Web1_ChiTietKhenThuongPhucLoi_LUH(Nullable<System.Guid> nhanVien, Nullable<System.Guid> kyTinhLuong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        /// <param name="kyTinhLuong">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ChiTietNgoaiGio_LUH_Result> spd_Web1_ChiTietNgoaiGio_LUH(Nullable<System.Guid> nhanVien, Nullable<System.Guid> kyTinhLuong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        /// <param name="kyTinhLuong">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ChiTietPhuCap_LUH_Result> spd_Web1_ChiTietPhuCap_LUH(Nullable<System.Guid> nhanVien, Nullable<System.Guid> kyTinhLuong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        /// <param name="kyTinhLuong">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ChiTietThueTNCN_LUH_Result> spd_Web1_ChiTietThueTNCN_LUH(Nullable<System.Guid> nhanVien, Nullable<System.Guid> kyTinhLuong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        /// <param name="kyTinhLuong">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ChiTietThuLaoGiangDay_LUH_Result> spd_Web1_ChiTietThuLaoGiangDay_LUH(Nullable<System.Guid> nhanVien, Nullable<System.Guid> kyTinhLuong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        /// <param name="kyTinhLuong">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ChiTietThuNhapCaNhan_LUH_Result> spd_Web1_ChiTietThuNhapCaNhan_LUH(Nullable<System.Guid> nhanVien, Nullable<System.Guid> kyTinhLuong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="nhanVien">No Metadata Documentation available.</param>
        /// <param name="kyTinhLuong">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_ChiTietThuNhapKhac_LUH_Result> spd_Web1_ChiTietThuNhapKhac_LUH(Nullable<System.Guid> nhanVien, Nullable<System.Guid> kyTinhLuong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="thongTinNhanVien">No Metadata Documentation available.</param>
        /// <param name="kyTinhLuong">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_BangThongTinThuNhap_LuongNganSach_Result> spd_Web1_BangThongTinThuNhap_LuongNganSach(Nullable<System.Guid> thongTinNhanVien, Nullable<System.Guid> kyTinhLuong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="thongTinNhanVien">No Metadata Documentation available.</param>
        /// <param name="kyTinhLuong">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_BangThongTinThuNhap_LuongTangThem_Result> spd_Web1_BangThongTinThuNhap_LuongTangThem(Nullable<System.Guid> thongTinNhanVien, Nullable<System.Guid> kyTinhLuong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="thongTinNhanVien">No Metadata Documentation available.</param>
        /// <param name="kyTinhLuong">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_BangThongTinThuNhap_Thue_Result> spd_Web1_BangThongTinThuNhap_Thue(Nullable<System.Guid> thongTinNhanVien, Nullable<System.Guid> kyTinhLuong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="thongTinNhanVien">No Metadata Documentation available.</param>
        /// <param name="kyTinhLuong">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_BangThongTinThuNhap_ThuNhapKhac_Result> spd_Web1_BangThongTinThuNhap_ThuNhapKhac(Nullable<System.Guid> thongTinNhanVien, Nullable<System.Guid> kyTinhLuong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="thongTinNhanVien">No Metadata Documentation available.</param>
        /// <param name="kyTinhLuong">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_BangThongTinThuNhap_TruyLinh_Result> spd_Web1_BangThongTinThuNhap_TruyLinh(Nullable<System.Guid> thongTinNhanVien, Nullable<System.Guid> kyTinhLuong);
    
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="thongTinNhanVien">No Metadata Documentation available.</param>
        /// <param name="kyTinhLuong">No Metadata Documentation available.</param>
        IEnumerable<spd_Web1_BangThongTinThuNhap_HeSo_Result> spd_Web1_BangThongTinThuNhap_HeSo(Nullable<System.Guid> thongTinNhanVien, Nullable<System.Guid> kyTinhLuong);
    

        #endregion

        #region ObjectContext Methods
    
    	T CreateObject<T>() where T : class;
    	
    	void DeleteObject(object entity);
    	
    	int SaveChanges(SaveOptions options);

        #endregion

    }
}
