//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	  Code duoc tao boi DESKTOP-PKPRC2J\NGOCBAO luc 01:49:02 ngay 20/01/2017
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
//using System.Data.EntityClient;
using System.Data.Entity.Core.EntityClient;
//using System.Data.Objects;
using System.Data.Entity.Core.Objects;
//using System.Data.Objects.DataClasses;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Runtime.Serialization;
using System.Xml.Serialization;


namespace HRMWeb_Business.Model
{
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ERPModel", Name="CC_ChamCongTheoNgayThayDoi")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CC_ChamCongTheoNgayThayDoi : ERP_Core.BaseEntityObject//EntityObject
    {
    	static CC_ChamCongTheoNgayThayDoi()
    	{
    
    		AfterStaticConstruction();
        }
        static partial void AfterStaticConstruction();
    
    	public CC_ChamCongTheoNgayThayDoi()
    	{
    
    		this.AfterConstruction();
        }
        partial void AfterConstruction();
    
        #region Factory Method
    
        /// <summary>
        /// Create a new CC_ChamCongTheoNgayThayDoi object.
        /// </summary>
        /// <param name="oid">Initial value of the Oid property.</param>
        public static CC_ChamCongTheoNgayThayDoi CreateCC_ChamCongTheoNgayThayDoi(System.Guid oid)
        {
            CC_ChamCongTheoNgayThayDoi cC_ChamCongTheoNgayThayDoi = new CC_ChamCongTheoNgayThayDoi();
            cC_ChamCongTheoNgayThayDoi.Oid = oid;
            return cC_ChamCongTheoNgayThayDoi;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public System.Guid Oid
        {
            get
            {
                return _oid;
            }
            set
            {
                if (_oid != value)
                {
        			System.Guid oldValue =  _oid;
        			bool stopChanging = false;
                    On_Oid_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("Oid");
        			if(!stopChanging)
        			{
        				_oid = StructuralObject.SetValidValue(value);
        				ReportPropertyChanged("Oid");
        				On_Oid_Changed(oldValue, _oid);//\\
        			}
                }
            }
        }
    	public static String Oid_PropertyName { get { return "Oid"; } }
        private System.Guid _oid;
        partial void On_Oid_Changing(System.Guid currentValue, ref System.Guid newValue, ref bool stopChanging);
        partial void On_Oid_Changed(System.Guid oldValue, System.Guid currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.Guid> IDHinhThucNghiThayDoi
        {
            get
            {
                return _iDHinhThucNghiThayDoi;
            }
            set
            {
    			Nullable<System.Guid> oldValue =  _iDHinhThucNghiThayDoi;
    			bool stopChanging = false;
                On_IDHinhThucNghiThayDoi_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("IDHinhThucNghiThayDoi");
    			if(!stopChanging)
    			{
    				_iDHinhThucNghiThayDoi = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("IDHinhThucNghiThayDoi");
    				On_IDHinhThucNghiThayDoi_Changed(oldValue, _iDHinhThucNghiThayDoi);//\\
    			}
            }
        }
    	public static String IDHinhThucNghiThayDoi_PropertyName { get { return "IDHinhThucNghiThayDoi"; } }
        private Nullable<System.Guid> _iDHinhThucNghiThayDoi;
        partial void On_IDHinhThucNghiThayDoi_Changing(Nullable<System.Guid> currentValue, ref Nullable<System.Guid> newValue, ref bool stopChanging);
        partial void On_IDHinhThucNghiThayDoi_Changed(Nullable<System.Guid> oldValue, Nullable<System.Guid> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.Guid> IDHinhThucNghiDonViCham
        {
            get
            {
                return _iDHinhThucNghiDonViCham;
            }
            set
            {
    			Nullable<System.Guid> oldValue =  _iDHinhThucNghiDonViCham;
    			bool stopChanging = false;
                On_IDHinhThucNghiDonViCham_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("IDHinhThucNghiDonViCham");
    			if(!stopChanging)
    			{
    				_iDHinhThucNghiDonViCham = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("IDHinhThucNghiDonViCham");
    				On_IDHinhThucNghiDonViCham_Changed(oldValue, _iDHinhThucNghiDonViCham);//\\
    			}
            }
        }
    	public static String IDHinhThucNghiDonViCham_PropertyName { get { return "IDHinhThucNghiDonViCham"; } }
        private Nullable<System.Guid> _iDHinhThucNghiDonViCham;
        partial void On_IDHinhThucNghiDonViCham_Changing(Nullable<System.Guid> currentValue, ref Nullable<System.Guid> newValue, ref bool stopChanging);
        partial void On_IDHinhThucNghiDonViCham_Changed(Nullable<System.Guid> oldValue, Nullable<System.Guid> currentValue);

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ERPModel", "FK_CC_ChamCongTheoNgayThayDoi_CC_ChamCongTheoNgay", "CC_ChamCongTheoNgay")]
        public CC_ChamCongTheoNgay CC_ChamCongTheoNgay
        {//test
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CC_ChamCongTheoNgay>("ERPModel.FK_CC_ChamCongTheoNgayThayDoi_CC_ChamCongTheoNgay", "CC_ChamCongTheoNgay").Value;
            }
            set
            {
    			bool stopChanging = false;
    			On_CC_ChamCongTheoNgay_Changing(ref value, ref stopChanging);//\\//
    			if(!stopChanging)
    			{
    				((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CC_ChamCongTheoNgay>("ERPModel.FK_CC_ChamCongTheoNgayThayDoi_CC_ChamCongTheoNgay", "CC_ChamCongTheoNgay").Value = value;
    				On_CC_ChamCongTheoNgay_Changed(this.CC_ChamCongTheoNgay);//\\//
    			}
    	    }
        }
    	public static String CC_ChamCongTheoNgay_ReferencePropertyName { get { return "CC_ChamCongTheoNgay"; } }
    	partial void On_CC_ChamCongTheoNgay_Changing(ref CC_ChamCongTheoNgay newValue, ref bool stopChanging);
    	partial void On_CC_ChamCongTheoNgay_Changed(CC_ChamCongTheoNgay currentValue);
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CC_ChamCongTheoNgay> CC_ChamCongTheoNgayReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CC_ChamCongTheoNgay>("ERPModel.FK_CC_ChamCongTheoNgayThayDoi_CC_ChamCongTheoNgay", "CC_ChamCongTheoNgay");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CC_ChamCongTheoNgay>("ERPModel.FK_CC_ChamCongTheoNgayThayDoi_CC_ChamCongTheoNgay", "CC_ChamCongTheoNgay", value);
                }
            }
        }

        #endregion

    }
}
