//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace HRMWeb_Business.Model
{
    using System;
    using System.Collections.Generic;
    [DataContract]
    public partial class DTO_ThongKeXetABCTheoThang
    {
        [DataMember]
        public String MaNhanSu { get; set; }
        [DataMember]
        public String HoVaTen { get; set; }
        [DataMember]
        public String TenPhongBan { get; set; }

        //[DataMember]
        //public String ThangNam { get; set; }
        [DataMember]
        public decimal NgayCong;

        [DataMember]
        public int NghiNuaNgay;
        [DataMember]
        public int NghiPhep;
        [DataMember]
        public int NghiRo;
        [DataMember]
        public int NghiThaiSan;
        [DataMember]
        public int NghiHe;

        [DataMember]
        public String Loai { get; set; }
        [DataMember]
        public String GhiChu { get; set; }

    }
   
}
