//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMWeb_Business.Model.MapObjectCreator
{
    using System;
    
    using System.Runtime.Serialization;
    [DataContract]
    public partial class spd_Report_Luong_ChiTietTongThuNhapTungNhanVienTest_Result1
    {
    	[DataMember]
        public Nullable<System.Guid> ThongTinNhanVien { get; set; }
    	[DataMember]
        public Nullable<decimal> SoTien { get; set; }
    }
}
