//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMWeb_Business.Model.MapObjectCreator
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;//[DataContract],[DataMember]
    [DataContract]
    public partial class Mdl_CC_CauHinhChamCong
    {
    	[DataMember]
        public System.Guid Oid { get; set; }
    	[DataMember]
        public int SoNgayNghiPhep { get; set; }
    	[DataMember]
        public string EmailSender { get; set; }
    	[DataMember]
        public string PassSender { get; set; }
    	[DataMember]
        public Nullable<int> SoNgayHieuTruongDuyet { get; set; }
    	[DataMember]
        public Nullable<System.Guid> CongTy { get; set; }
    	[DataMember]
        public Nullable<int> SoNgayDangKyNgoaiGio { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> NgayXoaPhepCu { get; set; }
    	[DataMember]
        public Nullable<decimal> SoNgayPhepTangThem { get; set; }
    	[DataMember]
        public Nullable<decimal> ThoiGianTangSoNgayPhep { get; set; }
    	[DataMember]
        public string Host { get; set; }
    	[DataMember]
        public Nullable<int> Port { get; set; }
    	[DataMember]
        public Nullable<bool> TruongDonViKhongDuyet { get; set; }
    }
}
