//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMWeb_Business.Model.MapObjectCreator
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;//[DataContract],[DataMember]
    [DataContract]
    public partial class Mdl_NamHoc
    {
        /*
    	ko xai
    	public Mdl_NamHoc()
        {
            this.CC_QuanLyNghiPhep = new HashSet<Mdl_CC_QuanLyNghiPhep>();
        }*/
    
    	[DataMember]
        public System.Guid Oid { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> NgayBatDau { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
    	[DataMember]
        public string TenNamHoc { get; set; }
    	[DataMember]
        public Nullable<int> OptimisticLockField { get; set; }
    	[DataMember]
        public Nullable<int> GCRecord { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> NgayVaoHoc { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> NgayKetThucHoc { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> NgayVaoHe { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> NgayKetThucHe { get; set; }
    	[DataMember]
        public Nullable<int> SoThangHoc { get; set; }
    
    	//[DataMember]
        //public virtual ICollection<Mdl_CC_QuanLyNghiPhep> CC_QuanLyNghiPhep { get; set; }
    }
}
