//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMWeb_Business.Model.MapObjectCreator
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;//[DataContract],[DataMember]
    [DataContract]
    public partial class Mdl_WebUserLogin
    {
    	[DataMember]
        public System.Guid Oid { get; set; }
    	[DataMember]
        public Nullable<System.Guid> WebUserId { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> Date { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> LoginTime { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> LogoutTime { get; set; }
    	[DataMember]
        public string IpAddress { get; set; }
    
    	//[DataMember]
        //public virtual Mdl_WebUser WebUser { get; set; }
    }
}
