//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMWeb_Business.Model.MapObjectCreator
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;//[DataContract],[DataMember]
    [DataContract]
    public partial class Mdl_CC_ChiTietChamCong
    {
    	[DataMember]
        public System.Guid Oid { get; set; }
    	[DataMember]
        public Nullable<System.Guid> QuanLyChamCong { get; set; }
    	[DataMember]
        public Nullable<System.Guid> BoPhan { get; set; }
    	[DataMember]
        public Nullable<System.Guid> ThongTinNhanVien { get; set; }
    	[DataMember]
        public Nullable<decimal> TongCong { get; set; }
    	[DataMember]
        public Nullable<decimal> NgayHuongLuong { get; set; }
    	[DataMember]
        public Nullable<decimal> NgayPhep { get; set; }
    	[DataMember]
        public Nullable<decimal> NgayKhongLuong { get; set; }
    	[DataMember]
        public Nullable<decimal> NgayHuongBHXH { get; set; }
    	[DataMember]
        public Nullable<decimal> NgayHe { get; set; }
    	[DataMember]
        public string DienGiai { get; set; }
    	[DataMember]
        public Nullable<bool> IsWeb { get; set; }
    	[DataMember]
        public Nullable<int> OptimisticLockField { get; set; }
    	[DataMember]
        public Nullable<int> GCRecord { get; set; }
    	[DataMember]
        public Nullable<bool> Khoa { get; set; }
    	[DataMember]
        public Nullable<decimal> CongChuanTheoLoaiGioLamViec { get; set; }
    	[DataMember]
        public Nullable<decimal> TongCongTruocDieuChinh { get; set; }
    	[DataMember]
        public Nullable<decimal> TongCongSauDieuChinh { get; set; }
    	[DataMember]
        public Nullable<decimal> NgayPhepBu { get; set; }
    
    	//[DataMember]
        //public virtual Mdl_CC_QuanLyChamCong CC_QuanLyChamCong { get; set; }
    	//[DataMember]
        //public virtual Mdl_ThongTinNhanVien ThongTinNhanVien1 { get; set; }
    	//[DataMember]
        //public virtual Mdl_BoPhan BoPhan1 { get; set; }
    }
}
