//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMWeb_Business.Model.MapObjectCreator
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;//[DataContract],[DataMember]
    [DataContract]
    public partial class Mdl_NhanVienThongTinLuong
    {
        /*
    	ko xai
    	public Mdl_NhanVienThongTinLuong()
        {
            this.NhanViens = new HashSet<Mdl_NhanVien>();
        }*/
    
    	[DataMember]
        public System.Guid Oid { get; set; }
    	[DataMember]
        public Nullable<byte> PhanLoai { get; set; }
    	[DataMember]
        public Nullable<bool> KhongTinhLuong { get; set; }
    	[DataMember]
        public Nullable<System.Guid> NgachLuong { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> NgayBoNhiemNgach { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> NgayHuongLuong { get; set; }
    	[DataMember]
        public Nullable<System.Guid> BacLuong { get; set; }
    	[DataMember]
        public Nullable<decimal> HeSoLuong { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> MocNangLuong { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> MocNangLuongDieuChinh { get; set; }
    	[DataMember]
        public string LyDoDieuChinh { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> MocNangLuongLanSau { get; set; }
    	[DataMember]
        public Nullable<bool> Huong85PhanTramLuong { get; set; }
    	[DataMember]
        public Nullable<bool> KhongDongBaoHiem { get; set; }
    	[DataMember]
        public Nullable<bool> KhongThamGiaCongDoan { get; set; }
    	[DataMember]
        public Nullable<bool> TamGiuLuong { get; set; }
    	[DataMember]
        public Nullable<decimal> LuongKhoan { get; set; }
    	[DataMember]
        public Nullable<decimal> HSPCChucVu { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> NgayHuongHSPCChucVu { get; set; }
    	[DataMember]
        public Nullable<decimal> HSPCDocHai { get; set; }
    	[DataMember]
        public Nullable<decimal> HSPCTrachNhiem { get; set; }
    	[DataMember]
        public Nullable<decimal> HSPCKhuVuc { get; set; }
    	[DataMember]
        public Nullable<decimal> HSPCKiemNhiem { get; set; }
    	[DataMember]
        public Nullable<decimal> HSPCLuuDong { get; set; }
    	[DataMember]
        public Nullable<decimal> HSPCUuDai { get; set; }
    	[DataMember]
        public Nullable<decimal> HSPCKhac { get; set; }
    	[DataMember]
        public Nullable<int> PhuCapUuDai { get; set; }
    	[DataMember]
        public Nullable<int> PhuCapDacThu { get; set; }
    	[DataMember]
        public Nullable<int> PhuCapDacBiet { get; set; }
    	[DataMember]
        public Nullable<decimal> ChenhLechBaoLuuLuong { get; set; }
    	[DataMember]
        public Nullable<int> VuotKhung { get; set; }
    	[DataMember]
        public Nullable<decimal> HSPCVuotKhung { get; set; }
    	[DataMember]
        public Nullable<decimal> ThamNien { get; set; }
    	[DataMember]
        public Nullable<decimal> HSPCThamNien { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> NgayHuongThamNien { get; set; }
    	[DataMember]
        public Nullable<int> PhuCapThuHut { get; set; }
    	[DataMember]
        public Nullable<decimal> HSPCChucVu1 { get; set; }
    	[DataMember]
        public Nullable<decimal> HSPCChucVu2 { get; set; }
    	[DataMember]
        public Nullable<decimal> HSPCChucVu3 { get; set; }
    	[DataMember]
        public Nullable<decimal> HSPCTrachNhiem1 { get; set; }
    	[DataMember]
        public Nullable<decimal> HSPCTrachNhiem2 { get; set; }
    	[DataMember]
        public Nullable<decimal> HSPCTrachNhiem3 { get; set; }
    	[DataMember]
        public Nullable<decimal> HSPCTrachNhiem4 { get; set; }
    	[DataMember]
        public Nullable<decimal> HSPCTrachNhiem5 { get; set; }
    	[DataMember]
        public Nullable<decimal> HSPCChucVuDang { get; set; }
    	[DataMember]
        public Nullable<decimal> HSPCChucVuDoan { get; set; }
    	[DataMember]
        public Nullable<decimal> HSPCChucVuCongDoan { get; set; }
    	[DataMember]
        public Nullable<decimal> PhuCapDienThoai { get; set; }
    	[DataMember]
        public Nullable<decimal> HSPCThiDua { get; set; }
    	[DataMember]
        public Nullable<decimal> HSPCChuyenMon { get; set; }
    	[DataMember]
        public Nullable<decimal> PhuCapTienAn { get; set; }
    	[DataMember]
        public Nullable<decimal> PhuCapTienXang { get; set; }
    	[DataMember]
        public Nullable<decimal> PhuCapTangThem { get; set; }
    	[DataMember]
        public string ThangNamTNCongTac { get; set; }
    	[DataMember]
        public Nullable<decimal> ThamNienCongTac { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> NgayCapNhatThamNienCongTac { get; set; }
    	[DataMember]
        public Nullable<decimal> PhuCapTrachNhiemCongViec { get; set; }
    	[DataMember]
        public Nullable<decimal> PhanTramThamNienHC { get; set; }
    	[DataMember]
        public Nullable<decimal> HSPCThamNienHC { get; set; }
    	[DataMember]
        public Nullable<decimal> HSPCKhoiHanhChinh { get; set; }
    	[DataMember]
        public Nullable<decimal> PhanTramTietChuan { get; set; }
    	[DataMember]
        public Nullable<decimal> HSLTangThem { get; set; }
    	[DataMember]
        public Nullable<int> TiLeTangThem { get; set; }
    	[DataMember]
        public Nullable<bool> KhongCuTru { get; set; }
    	[DataMember]
        public Nullable<int> SoNguoiPhuThuoc { get; set; }
    	[DataMember]
        public Nullable<int> SoThangGiamTru { get; set; }
    	[DataMember]
        public string MaSoThue { get; set; }
    	[DataMember]
        public Nullable<System.Guid> CoQuanThue { get; set; }
    	[DataMember]
        public Nullable<int> OptimisticLockField { get; set; }
    	[DataMember]
        public Nullable<int> GCRecord { get; set; }
    	[DataMember]
        public Nullable<decimal> MucDongBaoHiem { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> NgayHuongThamNienHC { get; set; }
    	[DataMember]
        public Nullable<int> PhuongThucTinhThue { get; set; }
    	[DataMember]
        public Nullable<bool> TinhThueTNCNMacDinh { get; set; }
    	[DataMember]
        public Nullable<decimal> ThuongHieuQuaTheoThangTruocDieuChinh { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> NgayDieuChinhMucThuNhap { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> NgayHuongTienTroCapChucVu { get; set; }
    	[DataMember]
        public Nullable<decimal> TienTroCapChucVu { get; set; }
    	[DataMember]
        public Nullable<decimal> ThuongHieuQuaTheoThang { get; set; }
    	[DataMember]
        public Nullable<decimal> MucLuong { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> NgayBatDauDongBaoHiem { get; set; }
    	[DataMember]
        public Nullable<int> PhuCapKhac { get; set; }
    	[DataMember]
        public Nullable<int> PhuCapDocHai { get; set; }
    	[DataMember]
        public Nullable<decimal> MucThuNhapTruocDieuChinh { get; set; }
    	[DataMember]
        public Nullable<decimal> TienLuongTruocThue { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> NgayCapMST { get; set; }
    	[DataMember]
        public Nullable<bool> DaBoNhiemNgach { get; set; }
    	[DataMember]
        public Nullable<decimal> SoThangKhongTinhThamNien { get; set; }
    	[DataMember]
        public Nullable<decimal> HSPCCongViec { get; set; }
    	[DataMember]
        public Nullable<int> PhuCapCongViec { get; set; }
    	[DataMember]
        public Nullable<decimal> PhuCapLaiXe { get; set; }
    	[DataMember]
        public Nullable<decimal> MucLuongTruocDieuChinh { get; set; }
    	[DataMember]
        public Nullable<decimal> HSPCChucVuBaoLuu { get; set; }
    	[DataMember]
        public Nullable<int> PhuCapKiemNhiem { get; set; }
    	[DataMember]
        public Nullable<bool> KhongDongBHXH { get; set; }
    	[DataMember]
        public Nullable<bool> KhongDongBHYT { get; set; }
    	[DataMember]
        public Nullable<bool> KhongDongBHTN { get; set; }
    	[DataMember]
        public Nullable<decimal> PhuCapBanAnNinh { get; set; }
    	[DataMember]
        public Nullable<decimal> PhuCapBanTuVe { get; set; }
    	[DataMember]
        public Nullable<decimal> HeSoH2 { get; set; }
    	[DataMember]
        public Nullable<decimal> SoNamLamChuyenVien { get; set; }
    	[DataMember]
        public Nullable<decimal> SoNamCongTac { get; set; }
    	[DataMember]
        public Nullable<System.Guid> HeSoH1 { get; set; }
    	[DataMember]
        public Nullable<System.Guid> HeSoH3 { get; set; }
    	[DataMember]
        public Nullable<System.Guid> TiLeTNTTTheoMucPCUD { get; set; }
    	[DataMember]
        public Nullable<System.Guid> HSLTangThemTheoThamNien { get; set; }
    	[DataMember]
        public Nullable<decimal> SoNgayLamViec { get; set; }
    	[DataMember]
        public Nullable<bool> LuongNET { get; set; }
    	[DataMember]
        public Nullable<decimal> HSPCChucVuBaoHiem { get; set; }
    	[DataMember]
        public Nullable<decimal> HSPCThamNienBaoHiem { get; set; }
    	[DataMember]
        public Nullable<decimal> PhuCapTPBHLD { get; set; }
    	[DataMember]
        public Nullable<decimal> HeSoTCDLD { get; set; }
    	[DataMember]
        public Nullable<decimal> HeSoTNTT { get; set; }
    	[DataMember]
        public Nullable<decimal> HeSoBangCap { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> NgayBatDauHuongThamNien { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> NgayHuongPhuCap { get; set; }
    	[DataMember]
        public Nullable<decimal> PhuCapDienThoaiTruocDieuChinh { get; set; }
    	[DataMember]
        public Nullable<decimal> PhuCapTrachNhiemCongViecTruocDieuChinh { get; set; }
    	[DataMember]
        public Nullable<decimal> PhuCapTienXangTruocDieuChinh { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> MocHuongThamNienTangThem { get; set; }
    	[DataMember]
        public Nullable<bool> KhongTinhSinhNhat { get; set; }
    	[DataMember]
        public Nullable<decimal> HSPCTrachNhiem6 { get; set; }
    
    	//[DataMember]
        //public virtual Mdl_NgachLuong NgachLuong1 { get; set; }
    	//[DataMember]
        //public virtual ICollection<Mdl_NhanVien> NhanViens { get; set; }
    }
}
