//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace HRMWeb_Business.Model
{
    using System;
    using System.Collections.Generic;
    [DataContract]
    public partial class DTO_KyChamCong
    {
        [DataMember]
        public Guid Oid { get; set; }
        [DataMember]
        public int Thang { get; set; }
        [DataMember]
        public int Nam { get; set; }
        [DataMember]
        public System.DateTime TuNgay { get; set; }
        [DataMember]
        public System.DateTime DenNgay { get; set; }
        [DataMember]
        public string TuNgayString { get; set; }
        [DataMember]
        public string DenNgayString { get; set; }
        [DataMember]
        public string TenKyChamCong { get; set; }

    }
}
