//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace HRMWeb_Business.Model
{
    using System;
    using System.Collections.Generic;
    [DataContract]
    public partial class DTO_QuanLyNghiPhep_InGiayNghiPhep_ChiTiet
    {
        [DataMember]
        public String TuNgay { get; set; }
        [DataMember]
        public String DenNgay { get; set; }
        [DataMember]
        public decimal? SoNgayXinNghi { get; set; }
        [DataMember]
        public decimal? SoNgayConLai { get; set; }
        [DataMember]
        public String LyDo { get; set; }
        [DataMember]
        public String NguoiXinNghi { get; set; }
        [DataMember]
        public String NguoiKiemTra { get; set; }
        [DataMember]
        public String TruongDonVi { get; set; }
        [DataMember]
        public String TCHCXacNhanNgay { get; set; }     
    }
}
