//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	  Code duoc tao boi DESKTOP-PKPRC2J\NGOCBAO luc 05:03:08 ngay 23/05/2017
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
//using System.Data.EntityClient;
using System.Data.Entity.Core.EntityClient;
//using System.Data.Objects;
using System.Data.Entity.Core.Objects;
//using System.Data.Objects.DataClasses;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Runtime.Serialization;
using System.Xml.Serialization;


namespace HRMWeb_Business.Model
{
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ERPModel", Name="CC_ChamCongNgayNghi")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CC_ChamCongNgayNghi : ERP_Core.BaseEntityObject//EntityObject
    {
    	static CC_ChamCongNgayNghi()
    	{
    
    		AfterStaticConstruction();
        }
        static partial void AfterStaticConstruction();
    
    	public CC_ChamCongNgayNghi()
    	{
    
    		this.AfterConstruction();
        }
        partial void AfterConstruction();
    
        #region Factory Method
    
        /// <summary>
        /// Create a new CC_ChamCongNgayNghi object.
        /// </summary>
        /// <param name="oid">Initial value of the Oid property.</param>
        public static CC_ChamCongNgayNghi CreateCC_ChamCongNgayNghi(System.Guid oid)
        {
            CC_ChamCongNgayNghi cC_ChamCongNgayNghi = new CC_ChamCongNgayNghi();
            cC_ChamCongNgayNghi.Oid = oid;
            return cC_ChamCongNgayNghi;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public System.Guid Oid
        {
            get
            {
                return _oid;
            }
            set
            {
                if (_oid != value)
                {
        			System.Guid oldValue =  _oid;
        			bool stopChanging = false;
                    On_Oid_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("Oid");
        			if(!stopChanging)
        			{
        				_oid = StructuralObject.SetValidValue(value);
        				ReportPropertyChanged("Oid");
        				On_Oid_Changed(oldValue, _oid);//\\
        			}
                }
            }
        }
    	public static String Oid_PropertyName { get { return "Oid"; } }
        private System.Guid _oid;
        partial void On_Oid_Changing(System.Guid currentValue, ref System.Guid newValue, ref bool stopChanging);
        partial void On_Oid_Changed(System.Guid oldValue, System.Guid currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.Guid> BangChamCongNgayNghi
        {
            get
            {
                return _bangChamCongNgayNghi;
            }
            set
            {
    			Nullable<System.Guid> oldValue =  _bangChamCongNgayNghi;
    			bool stopChanging = false;
                On_BangChamCongNgayNghi_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("BangChamCongNgayNghi");
    			if(!stopChanging)
    			{
    				_bangChamCongNgayNghi = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("BangChamCongNgayNghi");
    				On_BangChamCongNgayNghi_Changed(oldValue, _bangChamCongNgayNghi);//\\
    			}
            }
        }
    	public static String BangChamCongNgayNghi_PropertyName { get { return "BangChamCongNgayNghi"; } }
        private Nullable<System.Guid> _bangChamCongNgayNghi;
        partial void On_BangChamCongNgayNghi_Changing(Nullable<System.Guid> currentValue, ref Nullable<System.Guid> newValue, ref bool stopChanging);
        partial void On_BangChamCongNgayNghi_Changed(Nullable<System.Guid> oldValue, Nullable<System.Guid> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.Guid> TinhThanh
        {
            get
            {
                return _tinhThanh;
            }
            set
            {
    			Nullable<System.Guid> oldValue =  _tinhThanh;
    			bool stopChanging = false;
                On_TinhThanh_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TinhThanh");
    			if(!stopChanging)
    			{
    				_tinhThanh = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("TinhThanh");
    				On_TinhThanh_Changed(oldValue, _tinhThanh);//\\
    			}
            }
        }
    	public static String TinhThanh_PropertyName { get { return "TinhThanh"; } }
        private Nullable<System.Guid> _tinhThanh;
        partial void On_TinhThanh_Changing(Nullable<System.Guid> currentValue, ref Nullable<System.Guid> newValue, ref bool stopChanging);
        partial void On_TinhThanh_Changed(Nullable<System.Guid> oldValue, Nullable<System.Guid> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.DateTime> TuNgay
        {
            get
            {
                return _tuNgay;
            }
            set
            {
    			Nullable<System.DateTime> oldValue =  _tuNgay;
    			bool stopChanging = false;
                On_TuNgay_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TuNgay");
    			if(!stopChanging)
    			{
    				_tuNgay = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("TuNgay");
    				On_TuNgay_Changed(oldValue, _tuNgay);//\\
    			}
            }
        }
    	public static String TuNgay_PropertyName { get { return "TuNgay"; } }
        private Nullable<System.DateTime> _tuNgay;
        partial void On_TuNgay_Changing(Nullable<System.DateTime> currentValue, ref Nullable<System.DateTime> newValue, ref bool stopChanging);
        partial void On_TuNgay_Changed(Nullable<System.DateTime> oldValue, Nullable<System.DateTime> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.DateTime> DenNgay
        {
            get
            {
                return _denNgay;
            }
            set
            {
    			Nullable<System.DateTime> oldValue =  _denNgay;
    			bool stopChanging = false;
                On_DenNgay_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("DenNgay");
    			if(!stopChanging)
    			{
    				_denNgay = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("DenNgay");
    				On_DenNgay_Changed(oldValue, _denNgay);//\\
    			}
            }
        }
    	public static String DenNgay_PropertyName { get { return "DenNgay"; } }
        private Nullable<System.DateTime> _denNgay;
        partial void On_DenNgay_Changing(Nullable<System.DateTime> currentValue, ref Nullable<System.DateTime> newValue, ref bool stopChanging);
        partial void On_DenNgay_Changed(Nullable<System.DateTime> oldValue, Nullable<System.DateTime> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> SoNgay
        {
            get
            {
                return _soNgay;
            }
            set
            {
    			Nullable<int> oldValue =  _soNgay;
    			bool stopChanging = false;
                On_SoNgay_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("SoNgay");
    			if(!stopChanging)
    			{
    				_soNgay = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("SoNgay");
    				On_SoNgay_Changed(oldValue, _soNgay);//\\
    			}
            }
        }
    	public static String SoNgay_PropertyName { get { return "SoNgay"; } }
        private Nullable<int> _soNgay;
        partial void On_SoNgay_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_SoNgay_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<byte> XepLoaiDanhGia
        {
            get
            {
                return _xepLoaiDanhGia;
            }
            set
            {
    			Nullable<byte> oldValue =  _xepLoaiDanhGia;
    			bool stopChanging = false;
                On_XepLoaiDanhGia_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("XepLoaiDanhGia");
    			if(!stopChanging)
    			{
    				_xepLoaiDanhGia = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("XepLoaiDanhGia");
    				On_XepLoaiDanhGia_Changed(oldValue, _xepLoaiDanhGia);//\\
    			}
            }
        }
    	public static String XepLoaiDanhGia_PropertyName { get { return "XepLoaiDanhGia"; } }
        private Nullable<byte> _xepLoaiDanhGia;
        partial void On_XepLoaiDanhGia_Changing(Nullable<byte> currentValue, ref Nullable<byte> newValue, ref bool stopChanging);
        partial void On_XepLoaiDanhGia_Changed(Nullable<byte> oldValue, Nullable<byte> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string DienGiai
        {
            get
            {
                return _dienGiai;
            }
            set
            {
    			string oldValue =  _dienGiai;
    			bool stopChanging = false;
                On_DienGiai_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("DienGiai");
    			if(!stopChanging)
    			{
    				_dienGiai = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("DienGiai");
    				On_DienGiai_Changed(oldValue, _dienGiai);//\\
    			}
            }
        }
    	public static String DienGiai_PropertyName { get { return "DienGiai"; } }
        private string _dienGiai;
        partial void On_DienGiai_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_DienGiai_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> OptimisticLockField
        {
            get
            {
                return _optimisticLockField;
            }
            set
            {
    			Nullable<int> oldValue =  _optimisticLockField;
    			bool stopChanging = false;
                On_OptimisticLockField_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("OptimisticLockField");
    			if(!stopChanging)
    			{
    				_optimisticLockField = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("OptimisticLockField");
    				On_OptimisticLockField_Changed(oldValue, _optimisticLockField);//\\
    			}
            }
        }
    	public static String OptimisticLockField_PropertyName { get { return "OptimisticLockField"; } }
        private Nullable<int> _optimisticLockField;
        partial void On_OptimisticLockField_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_OptimisticLockField_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> GCRecord
        {
            get
            {
                return _gCRecord;
            }
            set
            {
    			Nullable<int> oldValue =  _gCRecord;
    			bool stopChanging = false;
                On_GCRecord_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("GCRecord");
    			if(!stopChanging)
    			{
    				_gCRecord = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("GCRecord");
    				On_GCRecord_Changed(oldValue, _gCRecord);//\\
    			}
            }
        }
    	public static String GCRecord_PropertyName { get { return "GCRecord"; } }
        private Nullable<int> _gCRecord;
        partial void On_GCRecord_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_GCRecord_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.Guid> IDBoPhan
        {
            get
            {
                return _iDBoPhan;
            }
            set
            {
    			Nullable<System.Guid> oldValue =  _iDBoPhan;
    			bool stopChanging = false;
                On_IDBoPhan_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("IDBoPhan");
    			if(!stopChanging)
    			{
    				_iDBoPhan = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("IDBoPhan");
    				On_IDBoPhan_Changed(oldValue, _iDBoPhan);//\\
    			}
            }
        }
    	public static String IDBoPhan_PropertyName { get { return "IDBoPhan"; } }
        private Nullable<System.Guid> _iDBoPhan;
        partial void On_IDBoPhan_Changing(Nullable<System.Guid> currentValue, ref Nullable<System.Guid> newValue, ref bool stopChanging);
        partial void On_IDBoPhan_Changed(Nullable<System.Guid> oldValue, Nullable<System.Guid> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.Guid> IDNhanVien
        {
            get
            {
                return _iDNhanVien;
            }
            set
            {
    			Nullable<System.Guid> oldValue =  _iDNhanVien;
    			bool stopChanging = false;
                On_IDNhanVien_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("IDNhanVien");
    			if(!stopChanging)
    			{
    				_iDNhanVien = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("IDNhanVien");
    				On_IDNhanVien_Changed(oldValue, _iDNhanVien);//\\
    			}
            }
        }
    	public static String IDNhanVien_PropertyName { get { return "IDNhanVien"; } }
        private Nullable<System.Guid> _iDNhanVien;
        partial void On_IDNhanVien_Changing(Nullable<System.Guid> currentValue, ref Nullable<System.Guid> newValue, ref bool stopChanging);
        partial void On_IDNhanVien_Changed(Nullable<System.Guid> oldValue, Nullable<System.Guid> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.Guid> IDHinhThucNghi
        {
            get
            {
                return _iDHinhThucNghi;
            }
            set
            {
    			Nullable<System.Guid> oldValue =  _iDHinhThucNghi;
    			bool stopChanging = false;
                On_IDHinhThucNghi_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("IDHinhThucNghi");
    			if(!stopChanging)
    			{
    				_iDHinhThucNghi = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("IDHinhThucNghi");
    				On_IDHinhThucNghi_Changed(oldValue, _iDHinhThucNghi);//\\
    			}
            }
        }
    	public static String IDHinhThucNghi_PropertyName { get { return "IDHinhThucNghi"; } }
        private Nullable<System.Guid> _iDHinhThucNghi;
        partial void On_IDHinhThucNghi_Changing(Nullable<System.Guid> currentValue, ref Nullable<System.Guid> newValue, ref bool stopChanging);
        partial void On_IDHinhThucNghi_Changed(Nullable<System.Guid> oldValue, Nullable<System.Guid> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.DateTime> NgayTao
        {
            get
            {
                return _ngayTao;
            }
            set
            {
    			Nullable<System.DateTime> oldValue =  _ngayTao;
    			bool stopChanging = false;
                On_NgayTao_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("NgayTao");
    			if(!stopChanging)
    			{
    				_ngayTao = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("NgayTao");
    				On_NgayTao_Changed(oldValue, _ngayTao);//\\
    			}
            }
        }
    	public static String NgayTao_PropertyName { get { return "NgayTao"; } }
        private Nullable<System.DateTime> _ngayTao;
        partial void On_NgayTao_Changing(Nullable<System.DateTime> currentValue, ref Nullable<System.DateTime> newValue, ref bool stopChanging);
        partial void On_NgayTao_Changed(Nullable<System.DateTime> oldValue, Nullable<System.DateTime> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.Guid> IDWebUser
        {
            get
            {
                return _iDWebUser;
            }
            set
            {
    			Nullable<System.Guid> oldValue =  _iDWebUser;
    			bool stopChanging = false;
                On_IDWebUser_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("IDWebUser");
    			if(!stopChanging)
    			{
    				_iDWebUser = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("IDWebUser");
    				On_IDWebUser_Changed(oldValue, _iDWebUser);//\\
    			}
            }
        }
    	public static String IDWebUser_PropertyName { get { return "IDWebUser"; } }
        private Nullable<System.Guid> _iDWebUser;
        partial void On_IDWebUser_Changing(Nullable<System.Guid> currentValue, ref Nullable<System.Guid> newValue, ref bool stopChanging);
        partial void On_IDWebUser_Changed(Nullable<System.Guid> oldValue, Nullable<System.Guid> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> SoNgayNghiPhepNamTruoc
        {
            get
            {
                return _soNgayNghiPhepNamTruoc;
            }
            set
            {
    			Nullable<int> oldValue =  _soNgayNghiPhepNamTruoc;
    			bool stopChanging = false;
                On_SoNgayNghiPhepNamTruoc_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("SoNgayNghiPhepNamTruoc");
    			if(!stopChanging)
    			{
    				_soNgayNghiPhepNamTruoc = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("SoNgayNghiPhepNamTruoc");
    				On_SoNgayNghiPhepNamTruoc_Changed(oldValue, _soNgayNghiPhepNamTruoc);//\\
    			}
            }
        }
    	public static String SoNgayNghiPhepNamTruoc_PropertyName { get { return "SoNgayNghiPhepNamTruoc"; } }
        private Nullable<int> _soNgayNghiPhepNamTruoc;
        partial void On_SoNgayNghiPhepNamTruoc_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_SoNgayNghiPhepNamTruoc_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> TruNgayPhepDiDuong
        {
            get
            {
                return _truNgayPhepDiDuong;
            }
            set
            {
    			Nullable<int> oldValue =  _truNgayPhepDiDuong;
    			bool stopChanging = false;
                On_TruNgayPhepDiDuong_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TruNgayPhepDiDuong");
    			if(!stopChanging)
    			{
    				_truNgayPhepDiDuong = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("TruNgayPhepDiDuong");
    				On_TruNgayPhepDiDuong_Changed(oldValue, _truNgayPhepDiDuong);//\\
    			}
            }
        }
    	public static String TruNgayPhepDiDuong_PropertyName { get { return "TruNgayPhepDiDuong"; } }
        private Nullable<int> _truNgayPhepDiDuong;
        partial void On_TruNgayPhepDiDuong_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_TruNgayPhepDiDuong_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.Guid> BoPhan
        {
            get
            {
                return _boPhan;
            }
            set
            {
    			Nullable<System.Guid> oldValue =  _boPhan;
    			bool stopChanging = false;
                On_BoPhan_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("BoPhan");
    			if(!stopChanging)
    			{
    				_boPhan = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("BoPhan");
    				On_BoPhan_Changed(oldValue, _boPhan);//\\
    			}
            }
        }
    	public static String BoPhan_PropertyName { get { return "BoPhan"; } }
        private Nullable<System.Guid> _boPhan;
        partial void On_BoPhan_Changing(Nullable<System.Guid> currentValue, ref Nullable<System.Guid> newValue, ref bool stopChanging);
        partial void On_BoPhan_Changed(Nullable<System.Guid> oldValue, Nullable<System.Guid> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.Guid> ThongTinNhanVien
        {
            get
            {
                return _thongTinNhanVien;
            }
            set
            {
    			Nullable<System.Guid> oldValue =  _thongTinNhanVien;
    			bool stopChanging = false;
                On_ThongTinNhanVien_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("ThongTinNhanVien");
    			if(!stopChanging)
    			{
    				_thongTinNhanVien = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("ThongTinNhanVien");
    				On_ThongTinNhanVien_Changed(oldValue, _thongTinNhanVien);//\\
    			}
            }
        }
    	public static String ThongTinNhanVien_PropertyName { get { return "ThongTinNhanVien"; } }
        private Nullable<System.Guid> _thongTinNhanVien;
        partial void On_ThongTinNhanVien_Changing(Nullable<System.Guid> currentValue, ref Nullable<System.Guid> newValue, ref bool stopChanging);
        partial void On_ThongTinNhanVien_Changed(Nullable<System.Guid> oldValue, Nullable<System.Guid> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.Guid> HinhThucNghi
        {
            get
            {
                return _hinhThucNghi;
            }
            set
            {
    			Nullable<System.Guid> oldValue =  _hinhThucNghi;
    			bool stopChanging = false;
                On_HinhThucNghi_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("HinhThucNghi");
    			if(!stopChanging)
    			{
    				_hinhThucNghi = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("HinhThucNghi");
    				On_HinhThucNghi_Changed(oldValue, _hinhThucNghi);//\\
    			}
            }
        }
    	public static String HinhThucNghi_PropertyName { get { return "HinhThucNghi"; } }
        private Nullable<System.Guid> _hinhThucNghi;
        partial void On_HinhThucNghi_Changing(Nullable<System.Guid> currentValue, ref Nullable<System.Guid> newValue, ref bool stopChanging);
        partial void On_HinhThucNghi_Changed(Nullable<System.Guid> oldValue, Nullable<System.Guid> currentValue);

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ERPModel", "FK_CC_ChamCongNgayNghi_BoPhan", "Department")]
        public Department Department
        {//test
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Department>("ERPModel.FK_CC_ChamCongNgayNghi_BoPhan", "Department").Value;
            }
            set
            {
    			bool stopChanging = false;
    			On_Department_Changing(ref value, ref stopChanging);//\\//
    			if(!stopChanging)
    			{
    				((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Department>("ERPModel.FK_CC_ChamCongNgayNghi_BoPhan", "Department").Value = value;
    				On_Department_Changed(this.Department);//\\//
    			}
    	    }
        }
    	public static String Department_ReferencePropertyName { get { return "Department"; } }
    	partial void On_Department_Changing(ref Department newValue, ref bool stopChanging);
    	partial void On_Department_Changed(Department currentValue);
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Department> DepartmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Department>("ERPModel.FK_CC_ChamCongNgayNghi_BoPhan", "Department");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Department>("ERPModel.FK_CC_ChamCongNgayNghi_BoPhan", "Department", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ERPModel", "FK_CC_ChamCongNgayNghi_BoPhan1", "Department")]
        public Department Department1
        {//test
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Department>("ERPModel.FK_CC_ChamCongNgayNghi_BoPhan1", "Department").Value;
            }
            set
            {
    			bool stopChanging = false;
    			On_Department1_Changing(ref value, ref stopChanging);//\\//
    			if(!stopChanging)
    			{
    				((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Department>("ERPModel.FK_CC_ChamCongNgayNghi_BoPhan1", "Department").Value = value;
    				On_Department1_Changed(this.Department1);//\\//
    			}
    	    }
        }
    	public static String Department1_ReferencePropertyName { get { return "Department1"; } }
    	partial void On_Department1_Changing(ref Department newValue, ref bool stopChanging);
    	partial void On_Department1_Changed(Department currentValue);
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Department> Department1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Department>("ERPModel.FK_CC_ChamCongNgayNghi_BoPhan1", "Department");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Department>("ERPModel.FK_CC_ChamCongNgayNghi_BoPhan1", "Department", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ERPModel", "FK_CC_ChamCongNgayNghi_CC_HinhThucNghi", "CC_HinhThucNghi")]
        public CC_HinhThucNghi CC_HinhThucNghi
        {//test
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CC_HinhThucNghi>("ERPModel.FK_CC_ChamCongNgayNghi_CC_HinhThucNghi", "CC_HinhThucNghi").Value;
            }
            set
            {
    			bool stopChanging = false;
    			On_CC_HinhThucNghi_Changing(ref value, ref stopChanging);//\\//
    			if(!stopChanging)
    			{
    				((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CC_HinhThucNghi>("ERPModel.FK_CC_ChamCongNgayNghi_CC_HinhThucNghi", "CC_HinhThucNghi").Value = value;
    				On_CC_HinhThucNghi_Changed(this.CC_HinhThucNghi);//\\//
    			}
    	    }
        }
    	public static String CC_HinhThucNghi_ReferencePropertyName { get { return "CC_HinhThucNghi"; } }
    	partial void On_CC_HinhThucNghi_Changing(ref CC_HinhThucNghi newValue, ref bool stopChanging);
    	partial void On_CC_HinhThucNghi_Changed(CC_HinhThucNghi currentValue);
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CC_HinhThucNghi> CC_HinhThucNghiReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CC_HinhThucNghi>("ERPModel.FK_CC_ChamCongNgayNghi_CC_HinhThucNghi", "CC_HinhThucNghi");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CC_HinhThucNghi>("ERPModel.FK_CC_ChamCongNgayNghi_CC_HinhThucNghi", "CC_HinhThucNghi", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ERPModel", "FK_CC_ChamCongNgayNghi_HoSo", "HoSo")]
        public HoSo HoSo
        {//test
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HoSo>("ERPModel.FK_CC_ChamCongNgayNghi_HoSo", "HoSo").Value;
            }
            set
            {
    			bool stopChanging = false;
    			On_HoSo_Changing(ref value, ref stopChanging);//\\//
    			if(!stopChanging)
    			{
    				((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HoSo>("ERPModel.FK_CC_ChamCongNgayNghi_HoSo", "HoSo").Value = value;
    				On_HoSo_Changed(this.HoSo);//\\//
    			}
    	    }
        }
    	public static String HoSo_ReferencePropertyName { get { return "HoSo"; } }
    	partial void On_HoSo_Changing(ref HoSo newValue, ref bool stopChanging);
    	partial void On_HoSo_Changed(HoSo currentValue);
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<HoSo> HoSoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HoSo>("ERPModel.FK_CC_ChamCongNgayNghi_HoSo", "HoSo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<HoSo>("ERPModel.FK_CC_ChamCongNgayNghi_HoSo", "HoSo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ERPModel", "FK_CC_ChamCongNgayNghi_ThongTinNhanVien", "ThongTinNhanVien")]
        public ThongTinNhanVien ThongTinNhanVien1
        {//test
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ThongTinNhanVien>("ERPModel.FK_CC_ChamCongNgayNghi_ThongTinNhanVien", "ThongTinNhanVien").Value;
            }
            set
            {
    			bool stopChanging = false;
    			On_ThongTinNhanVien1_Changing(ref value, ref stopChanging);//\\//
    			if(!stopChanging)
    			{
    				((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ThongTinNhanVien>("ERPModel.FK_CC_ChamCongNgayNghi_ThongTinNhanVien", "ThongTinNhanVien").Value = value;
    				On_ThongTinNhanVien1_Changed(this.ThongTinNhanVien1);//\\//
    			}
    	    }
        }
    	public static String ThongTinNhanVien1_ReferencePropertyName { get { return "ThongTinNhanVien1"; } }
    	partial void On_ThongTinNhanVien1_Changing(ref ThongTinNhanVien newValue, ref bool stopChanging);
    	partial void On_ThongTinNhanVien1_Changed(ThongTinNhanVien currentValue);
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ThongTinNhanVien> ThongTinNhanVien1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ThongTinNhanVien>("ERPModel.FK_CC_ChamCongNgayNghi_ThongTinNhanVien", "ThongTinNhanVien");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ThongTinNhanVien>("ERPModel.FK_CC_ChamCongNgayNghi_ThongTinNhanVien", "ThongTinNhanVien", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ERPModel", "FK_CC_ChamCongNgayNghi_TinhThanh", "TinhThanh")]
        public TinhThanh TinhThanh1
        {//test
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TinhThanh>("ERPModel.FK_CC_ChamCongNgayNghi_TinhThanh", "TinhThanh").Value;
            }
            set
            {
    			bool stopChanging = false;
    			On_TinhThanh1_Changing(ref value, ref stopChanging);//\\//
    			if(!stopChanging)
    			{
    				((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TinhThanh>("ERPModel.FK_CC_ChamCongNgayNghi_TinhThanh", "TinhThanh").Value = value;
    				On_TinhThanh1_Changed(this.TinhThanh1);//\\//
    			}
    	    }
        }
    	public static String TinhThanh1_ReferencePropertyName { get { return "TinhThanh1"; } }
    	partial void On_TinhThanh1_Changing(ref TinhThanh newValue, ref bool stopChanging);
    	partial void On_TinhThanh1_Changed(TinhThanh currentValue);
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TinhThanh> TinhThanh1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TinhThanh>("ERPModel.FK_CC_ChamCongNgayNghi_TinhThanh", "TinhThanh");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TinhThanh>("ERPModel.FK_CC_ChamCongNgayNghi_TinhThanh", "TinhThanh", value);
                }
            }
        }

        #endregion

    }
}
