//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	  Code duoc tao boi DESKTOP-O8ODB0C\thevi luc 09:44:27 ngay 17/09/2019
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
//using System.Data.EntityClient;
using System.Data.Entity.Core.EntityClient;
//using System.Data.Objects;
using System.Data.Entity.Core.Objects;
//using System.Data.Objects.DataClasses;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Runtime.Serialization;
using System.Xml.Serialization;


namespace HRMWeb_Business.Model
{
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ERPModel", Name="NgayLamBuTrongNam")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NgayLamBuTrongNam : ERP_Core.BaseEntityObject//EntityObject
    {
    	static NgayLamBuTrongNam()
    	{
    
    		AfterStaticConstruction();
        }
        static partial void AfterStaticConstruction();
    
    	public NgayLamBuTrongNam()
    	{
    
    		this.AfterConstruction();
        }
        partial void AfterConstruction();
    
        #region Factory Method
    
        /// <summary>
        /// Create a new NgayLamBuTrongNam object.
        /// </summary>
        /// <param name="oid">Initial value of the Oid property.</param>
        public static NgayLamBuTrongNam CreateNgayLamBuTrongNam(System.Guid oid)
        {
            NgayLamBuTrongNam ngayLamBuTrongNam = new NgayLamBuTrongNam();
            ngayLamBuTrongNam.Oid = oid;
            return ngayLamBuTrongNam;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public System.Guid Oid
        {
            get
            {
                return _oid;
            }
            set
            {
                if (_oid != value)
                {
        			System.Guid oldValue =  _oid;
        			bool stopChanging = false;
                    On_Oid_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("Oid");
        			if(!stopChanging)
        			{
        				_oid = StructuralObject.SetValidValue(value);
        				ReportPropertyChanged("Oid");
        				On_Oid_Changed(oldValue, _oid);//\\
        			}
                }
            }
        }
    	public static String Oid_PropertyName { get { return "Oid"; } }
        private System.Guid _oid;
        partial void On_Oid_Changing(System.Guid currentValue, ref System.Guid newValue, ref bool stopChanging);
        partial void On_Oid_Changed(System.Guid oldValue, System.Guid currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.Guid> QuanLyNgayLamBuTrongNam
        {
            get
            {
                return _quanLyNgayLamBuTrongNam;
            }
            set
            {
    			Nullable<System.Guid> oldValue =  _quanLyNgayLamBuTrongNam;
    			bool stopChanging = false;
                On_QuanLyNgayLamBuTrongNam_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("QuanLyNgayLamBuTrongNam");
    			if(!stopChanging)
    			{
    				_quanLyNgayLamBuTrongNam = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("QuanLyNgayLamBuTrongNam");
    				On_QuanLyNgayLamBuTrongNam_Changed(oldValue, _quanLyNgayLamBuTrongNam);//\\
    			}
            }
        }
    	public static String QuanLyNgayLamBuTrongNam_PropertyName { get { return "QuanLyNgayLamBuTrongNam"; } }
        private Nullable<System.Guid> _quanLyNgayLamBuTrongNam;
        partial void On_QuanLyNgayLamBuTrongNam_Changing(Nullable<System.Guid> currentValue, ref Nullable<System.Guid> newValue, ref bool stopChanging);
        partial void On_QuanLyNgayLamBuTrongNam_Changed(Nullable<System.Guid> oldValue, Nullable<System.Guid> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string TenNgayLamBu
        {
            get
            {
                return _tenNgayLamBu;
            }
            set
            {
    			string oldValue =  _tenNgayLamBu;
    			bool stopChanging = false;
                On_TenNgayLamBu_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("TenNgayLamBu");
    			if(!stopChanging)
    			{
    				_tenNgayLamBu = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("TenNgayLamBu");
    				On_TenNgayLamBu_Changed(oldValue, _tenNgayLamBu);//\\
    			}
            }
        }
    	public static String TenNgayLamBu_PropertyName { get { return "TenNgayLamBu"; } }
        private string _tenNgayLamBu;
        partial void On_TenNgayLamBu_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_TenNgayLamBu_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.DateTime> NgayLamBu
        {
            get
            {
                return _ngayLamBu;
            }
            set
            {
    			Nullable<System.DateTime> oldValue =  _ngayLamBu;
    			bool stopChanging = false;
                On_NgayLamBu_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("NgayLamBu");
    			if(!stopChanging)
    			{
    				_ngayLamBu = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("NgayLamBu");
    				On_NgayLamBu_Changed(oldValue, _ngayLamBu);//\\
    			}
            }
        }
    	public static String NgayLamBu_PropertyName { get { return "NgayLamBu"; } }
        private Nullable<System.DateTime> _ngayLamBu;
        partial void On_NgayLamBu_Changing(Nullable<System.DateTime> currentValue, ref Nullable<System.DateTime> newValue, ref bool stopChanging);
        partial void On_NgayLamBu_Changed(Nullable<System.DateTime> oldValue, Nullable<System.DateTime> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> OptimisticLockField
        {
            get
            {
                return _optimisticLockField;
            }
            set
            {
    			Nullable<int> oldValue =  _optimisticLockField;
    			bool stopChanging = false;
                On_OptimisticLockField_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("OptimisticLockField");
    			if(!stopChanging)
    			{
    				_optimisticLockField = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("OptimisticLockField");
    				On_OptimisticLockField_Changed(oldValue, _optimisticLockField);//\\
    			}
            }
        }
    	public static String OptimisticLockField_PropertyName { get { return "OptimisticLockField"; } }
        private Nullable<int> _optimisticLockField;
        partial void On_OptimisticLockField_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_OptimisticLockField_Changed(Nullable<int> oldValue, Nullable<int> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> GCRecord
        {
            get
            {
                return _gCRecord;
            }
            set
            {
    			Nullable<int> oldValue =  _gCRecord;
    			bool stopChanging = false;
                On_GCRecord_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("GCRecord");
    			if(!stopChanging)
    			{
    				_gCRecord = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("GCRecord");
    				On_GCRecord_Changed(oldValue, _gCRecord);//\\
    			}
            }
        }
    	public static String GCRecord_PropertyName { get { return "GCRecord"; } }
        private Nullable<int> _gCRecord;
        partial void On_GCRecord_Changing(Nullable<int> currentValue, ref Nullable<int> newValue, ref bool stopChanging);
        partial void On_GCRecord_Changed(Nullable<int> oldValue, Nullable<int> currentValue);

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ERPModel", "FK_NgayLamBuTrongNam_QuanLyNgayLamBuTrongNam", "QuanLyNgayLamBuTrongNam")]
        public QuanLyNgayLamBuTrongNam QuanLyNgayLamBuTrongNam1
        {//test
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<QuanLyNgayLamBuTrongNam>("ERPModel.FK_NgayLamBuTrongNam_QuanLyNgayLamBuTrongNam", "QuanLyNgayLamBuTrongNam").Value;
            }
            set
            {
    			bool stopChanging = false;
    			On_QuanLyNgayLamBuTrongNam1_Changing(ref value, ref stopChanging);//\\//
    			if(!stopChanging)
    			{
    				((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<QuanLyNgayLamBuTrongNam>("ERPModel.FK_NgayLamBuTrongNam_QuanLyNgayLamBuTrongNam", "QuanLyNgayLamBuTrongNam").Value = value;
    				On_QuanLyNgayLamBuTrongNam1_Changed(this.QuanLyNgayLamBuTrongNam1);//\\//
    			}
    	    }
        }
    	public static String QuanLyNgayLamBuTrongNam1_ReferencePropertyName { get { return "QuanLyNgayLamBuTrongNam1"; } }
    	partial void On_QuanLyNgayLamBuTrongNam1_Changing(ref QuanLyNgayLamBuTrongNam newValue, ref bool stopChanging);
    	partial void On_QuanLyNgayLamBuTrongNam1_Changed(QuanLyNgayLamBuTrongNam currentValue);
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<QuanLyNgayLamBuTrongNam> QuanLyNgayLamBuTrongNam1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<QuanLyNgayLamBuTrongNam>("ERPModel.FK_NgayLamBuTrongNam_QuanLyNgayLamBuTrongNam", "QuanLyNgayLamBuTrongNam");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<QuanLyNgayLamBuTrongNam>("ERPModel.FK_NgayLamBuTrongNam_QuanLyNgayLamBuTrongNam", "QuanLyNgayLamBuTrongNam", value);
                }
            }
        }

        #endregion

    }
}
