//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	  Code duoc tao boi DESKTOP-PKPRC2J\NGOCBAO luc 12:14:05 ngay 06/04/2019
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
//using System.Data.EntityClient;
using System.Data.Entity.Core.EntityClient;
//using System.Data.Objects;
using System.Data.Entity.Core.Objects;
//using System.Data.Objects.DataClasses;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Runtime.Serialization;
using System.Xml.Serialization;


namespace HRMWeb_Business.Model
{
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ERPModel", Name="CC_MailManager")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CC_MailManager : ERP_Core.BaseEntityObject//EntityObject
    {
    	static CC_MailManager()
    	{
    
    		AfterStaticConstruction();
        }
        static partial void AfterStaticConstruction();
    
    	public CC_MailManager()
    	{
    
    		this.AfterConstruction();
        }
        partial void AfterConstruction();
    
        #region Factory Method
    
        /// <summary>
        /// Create a new CC_MailManager object.
        /// </summary>
        /// <param name="oid">Initial value of the Oid property.</param>
        public static CC_MailManager CreateCC_MailManager(System.Guid oid)
        {
            CC_MailManager cC_MailManager = new CC_MailManager();
            cC_MailManager.Oid = oid;
            return cC_MailManager;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public System.Guid Oid
        {
            get
            {
                return _oid;
            }
            set
            {
                if (_oid != value)
                {
        			System.Guid oldValue =  _oid;
        			bool stopChanging = false;
                    On_Oid_Changing(oldValue, ref value, ref stopChanging);
                    ReportPropertyChanging("Oid");
        			if(!stopChanging)
        			{
        				_oid = StructuralObject.SetValidValue(value);
        				ReportPropertyChanged("Oid");
        				On_Oid_Changed(oldValue, _oid);//\\
        			}
                }
            }
        }
    	public static String Oid_PropertyName { get { return "Oid"; } }
        private System.Guid _oid;
        partial void On_Oid_Changing(System.Guid currentValue, ref System.Guid newValue, ref bool stopChanging);
        partial void On_Oid_Changed(System.Guid oldValue, System.Guid currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string Title
        {
            get
            {
                return _title;
            }
            set
            {
    			string oldValue =  _title;
    			bool stopChanging = false;
                On_Title_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("Title");
    			if(!stopChanging)
    			{
    				_title = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("Title");
    				On_Title_Changed(oldValue, _title);//\\
    			}
            }
        }
    	public static String Title_PropertyName { get { return "Title"; } }
        private string _title;
        partial void On_Title_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_Title_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string Contents
        {
            get
            {
                return _contents;
            }
            set
            {
    			string oldValue =  _contents;
    			bool stopChanging = false;
                On_Contents_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("Contents");
    			if(!stopChanging)
    			{
    				_contents = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("Contents");
    				On_Contents_Changed(oldValue, _contents);//\\
    			}
            }
        }
    	public static String Contents_PropertyName { get { return "Contents"; } }
        private string _contents;
        partial void On_Contents_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_Contents_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string ReceiverEmail
        {
            get
            {
                return _receiverEmail;
            }
            set
            {
    			string oldValue =  _receiverEmail;
    			bool stopChanging = false;
                On_ReceiverEmail_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("ReceiverEmail");
    			if(!stopChanging)
    			{
    				_receiverEmail = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("ReceiverEmail");
    				On_ReceiverEmail_Changed(oldValue, _receiverEmail);//\\
    			}
            }
        }
    	public static String ReceiverEmail_PropertyName { get { return "ReceiverEmail"; } }
        private string _receiverEmail;
        partial void On_ReceiverEmail_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_ReceiverEmail_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.DateTime> SendDate
        {
            get
            {
                return _sendDate;
            }
            set
            {
    			Nullable<System.DateTime> oldValue =  _sendDate;
    			bool stopChanging = false;
                On_SendDate_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("SendDate");
    			if(!stopChanging)
    			{
    				_sendDate = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("SendDate");
    				On_SendDate_Changed(oldValue, _sendDate);//\\
    			}
            }
        }
    	public static String SendDate_PropertyName { get { return "SendDate"; } }
        private Nullable<System.DateTime> _sendDate;
        partial void On_SendDate_Changing(Nullable<System.DateTime> currentValue, ref Nullable<System.DateTime> newValue, ref bool stopChanging);
        partial void On_SendDate_Changed(Nullable<System.DateTime> oldValue, Nullable<System.DateTime> currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return _fileName;
            }
            set
            {
    			string oldValue =  _fileName;
    			bool stopChanging = false;
                On_FileName_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("FileName");
    			if(!stopChanging)
    			{
    				_fileName = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("FileName");
    				On_FileName_Changed(oldValue, _fileName);//\\
    			}
            }
        }
    	public static String FileName_PropertyName { get { return "FileName"; } }
        private string _fileName;
        partial void On_FileName_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_FileName_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string SendEmail
        {
            get
            {
                return _sendEmail;
            }
            set
            {
    			string oldValue =  _sendEmail;
    			bool stopChanging = false;
                On_SendEmail_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("SendEmail");
    			if(!stopChanging)
    			{
    				_sendEmail = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("SendEmail");
    				On_SendEmail_Changed(oldValue, _sendEmail);//\\
    			}
            }
        }
    	public static String SendEmail_PropertyName { get { return "SendEmail"; } }
        private string _sendEmail;
        partial void On_SendEmail_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_SendEmail_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string SendPass
        {
            get
            {
                return _sendPass;
            }
            set
            {
    			string oldValue =  _sendPass;
    			bool stopChanging = false;
                On_SendPass_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("SendPass");
    			if(!stopChanging)
    			{
    				_sendPass = StructuralObject.SetValidValue(value, true);
    				ReportPropertyChanged("SendPass");
    				On_SendPass_Changed(oldValue, _sendPass);//\\
    			}
            }
        }
    	public static String SendPass_PropertyName { get { return "SendPass"; } }
        private string _sendPass;
        partial void On_SendPass_Changing(string currentValue, ref string newValue, ref bool stopChanging);
        partial void On_SendPass_Changed(string oldValue, string currentValue);
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.Guid> IDWebUser
        {
            get
            {
                return _iDWebUser;
            }
            set
            {
    			Nullable<System.Guid> oldValue =  _iDWebUser;
    			bool stopChanging = false;
                On_IDWebUser_Changing(oldValue, ref value, ref stopChanging);
                ReportPropertyChanging("IDWebUser");
    			if(!stopChanging)
    			{
    				_iDWebUser = StructuralObject.SetValidValue(value);
    				ReportPropertyChanged("IDWebUser");
    				On_IDWebUser_Changed(oldValue, _iDWebUser);//\\
    			}
            }
        }
    	public static String IDWebUser_PropertyName { get { return "IDWebUser"; } }
        private Nullable<System.Guid> _iDWebUser;
        partial void On_IDWebUser_Changing(Nullable<System.Guid> currentValue, ref Nullable<System.Guid> newValue, ref bool stopChanging);
        partial void On_IDWebUser_Changed(Nullable<System.Guid> oldValue, Nullable<System.Guid> currentValue);

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ERPModel", "FK_CC_MailManager_WebUsers", "WebUser")]
        public WebUser WebUser
        {//test
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WebUser>("ERPModel.FK_CC_MailManager_WebUsers", "WebUser").Value;
            }
            set
            {
    			bool stopChanging = false;
    			On_WebUser_Changing(ref value, ref stopChanging);//\\//
    			if(!stopChanging)
    			{
    				((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WebUser>("ERPModel.FK_CC_MailManager_WebUsers", "WebUser").Value = value;
    				On_WebUser_Changed(this.WebUser);//\\//
    			}
    	    }
        }
    	public static String WebUser_ReferencePropertyName { get { return "WebUser"; } }
    	partial void On_WebUser_Changing(ref WebUser newValue, ref bool stopChanging);
    	partial void On_WebUser_Changed(WebUser currentValue);
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<WebUser> WebUserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WebUser>("ERPModel.FK_CC_MailManager_WebUsers", "WebUser");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<WebUser>("ERPModel.FK_CC_MailManager_WebUsers", "WebUser", value);
                }
            }
        }

        #endregion

    }
}
