
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	  Code duoc tao boi SERVERERP\tai luc 10:09:31 ngay 29/07/2016
// </auto-generated>
//------------------------------------------------------------------------------

//using System.Data.Objects.DataClasses;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Data.Entity.Core.Metadata.Edm;
[assembly: EdmSchemaAttribute()]

#region EDM Relationship Metadata

#endregion

