//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace HRMWeb_Business.Model
{
    using System;
    using System.Collections.Generic;
    [DataContract]
    public partial class DTO_HinhThucNghi
    {
        [DataMember]
        public System.Guid Oid { get; set; }
        [DataMember]
        public string MaQuanLy { get; set; }
        [DataMember]
        public string TenHinhThucNghi { get; set; }
        [DataMember]
        public string KyHieu { get; set; }
        [DataMember]
        public Nullable<byte> PhanLoai { get; set; }
        [DataMember]
        public Nullable<decimal> GiaTri { get; set; }
        [DataMember]
        public Nullable<decimal> SoNgayToiDa { get; set; }

        //public Nullable<int> OptimisticLockField { get; set; }
        //public Nullable<int> GCRecord { get; set; }

        //public virtual ICollection<Mdl_CC_ChamCongTheoNgay> CC_ChamCongTheoNgay { get; set; }
    }
}
